### ISSUE TITLE
Update to 2.0.4 : *field* is already defined

### ISSUE THREAD

**Issue by pierre-H** [api-platform/core#1017]
Hello,

First, thank you for your work : Api Platform is great !!!

I just updated from Api Platform from 2.0.3 to 2.0.6 and when I try to go on a GET list, I've got a doctine error for this request : 

> [Semantical Error] line 0, col 604 near 'mouv2 WHERE mouv2.userId': Error: 'mouv2' is already defined.

Do you need the SQL query ?

Thank you !

**Comment by pierre-H** [comment]
After investigation, the problem is form the 2.0.4 version

**Comment by soyuka** [comment]
Yes, please update to 2.0.6 should be fine!

**Comment by pierre-H** [comment]
@soyuka I tried first with 2.0.6 and I had the problem. Then, because it was an update from 2.0.3 o 2.0.6, I wanted to know which version exactly creates the bug. So I tried with 2.0.4 and I had the bug so to update to 2.0.6 will not fix the problem because I already tried it.

**Comment by soyuka** [comment]
Please give a way to reproduce (ie some entities + resource definition).

**Comment by Simperfit** [comment]
Could you please do the following ? 

- Fork the [API Platform Standard Edition](https://github.com/api-platform/api-platform)
- Do the minimum modification to reproduce the bug
- Post the link in here

We will test that and confirm.

**Comment by pierre-H** [comment]
I close this issue since, fortunately, I don't know how to reproduce the bug.
So if this comes back, I will do @Simperfit steps.

**Comment by guilhemVB** [comment]
Hello,

I think I'm facing the same issue. I've a ManyToOne relation between entity Stage and entity Voyage (a voyage have many Stage), and when I send a GET request to a specific Stage, I've the following error :

```
near "voyage WHERE": Error: "voyage" is already defined.
```

You can see a complet error trace on travis : https://travis-ci.org/guilhemVB/api-lms/builds/300156563#L1640

The two entities : [Stage](https://github.com/guilhemVB/api-lms/blob/master/src/AppBundle/Entity/Stage.php#L44) and [Voyage](https://github.com/guilhemVB/api-lms/blob/master/src/AppBundle/Entity/Voyage.php#L99)

$voyage attribute is not supposed to appear on serialize Stage object, because $voyage is not in normalization_context group.

Am I doing something wrong ? Do you have any idea ?

Thanks
Guilhem
