### ISSUE TITLE
Add a filter to select specific fields

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#1083]
`http://example.com/books?fields=title,description` should serialize only the specified properties.

The filter should **not** be Doctrine dependent. It must implement the `FilterInterface` (to appear in the documentation) and decorate the `SerializerContextBuilder` to use [the new `attributes` context option](https://github.com/symfony/symfony/pull/18834) available in Symfony 3.3.

This filter should throw an exception if the Serializer version is < to 3.3.

**Comment by meyerbaptiste** [comment]
How does this feature deal with serialization groups @dunglas?

**Comment by dunglas** [comment]
In the Symfony serializer, groups are applied first, then fields are applied. A field cannot be serialized if it is hidden by a group. I think we respect this behavior.

**Comment by bwegrzyn** [comment]
Would this work with nested properties? For example `?fields=user.email`

**Comment by dunglas** [comment]
Yes, the Symfony serializer supports this.

**Comment by mitalcoi** [comment]
Great feature, but maybe we should to avoid using key names without "_" prefix?
It will be more safe design:
```http://example.com/books?_fields=title,description```
It is also related to #1082  
```http://example.com/books?_groups=group1,group2```

**Comment by dunglas** [comment]
Existing keys such as page are not prefixed. We cannot use this convention now, it would not be consistent. However all keys are already configurable. It will be the same for this one.

**Comment by Simperfit** [comment]
This has been merged

**Comment by erikkubica** [comment]
Sorry for being stupid, i am searching for like a hour if this is possible accross related issues, but still don´t know if its possible. 

I make a get request /api/schedules?fields[]=id&fields[]=form&fields[]=status&fields[]=sent and it returns all the fields. I have tried using _field, field, _property, property, _properties, properties none of them worked.

The situation is, that for listing I don´t need to request all fields/properties, and as result I end up pulling 10 times more data because it also contains XtoY relationships which are connected using groups, since I need them when I pull a single entity.

There would be no issues if i can just /api/schedules?groups[]=schedules.list (or the example above, but groups seems to be more effective) and i will only pull fields that I need.
