### ISSUE TITLE
Tree : use IRI instead of normalization context

### ISSUE THREAD

**Issue by pierre-H** [api-platform/core#1130]
Hello !

I've got an entity with a tree : 
```php
/**
 * @ApiResource(
 *     itemOperations={
 *          "get"={"method"="GET", "normalization_context"={"groups"={"read"}}},
 *     }
 *  )
 */
class Comment {
    /**
     * @var string
     * @Groups({"read"})
     */
    private $title;

    /**
     * @var Comment
     * @Groups({"read"})
     */
    private $parent;
}
```

I'd like to have the IRI parent, not the content.
The problem here is that I get :
```json
{
    "title": "My first post",
    "parent": {
        "title": "My second post"
    }
}
```

instead of : 
```json
{
    "title": "My first post",
    "parent": "/posts/2"
}
```

I know that there is the `@MaxDepth` annotation, but it doesn't generate IRI. Is there another solution ?

**Comment by soyuka** [comment]
Dooh, I had the same issue yesterday. The solution would be to implement the `circular_reference_handler` configuration in symfony. 

I can't give you my implementation because I use another normalization implementation :/.

**Comment by pierre-H** [comment]
@soyuka `circular_reference_handler` is when the serializer finds a circle. But in my case, there is no circle.

**Comment by soyuka** [comment]
Oh my bad, thought you had children too. For this to work you need to use some kind of dynamic group.

Or maybe we're missing something for the MaxDepth implementation to do what you said, I'll look into this becaused I also expected that result and it didn't happend.

Another solution is to use some kind of dynamic group. Indeed you serialize with `read` on `Comment` and because `parent` is also an instance of `Comment` you'll get the same fields.

**Comment by teohhanhui** [comment]
Related (same?): api-platform/core#1001

**Comment by pierre-H** [comment]
@teohhanhui Yes you're right : it's the same question. I still don't have a good solution for this ...

**Comment by teohhanhui** [comment]
Unfortunately, I don't have a good solution for this either... We'll need to put our minds (and fingers) together to come up with something...

**Comment by silverbackdan** [comment]
This can be closed as https://github.com/api-platform/core/pull/1528 is merged

**Comment by pierre-H** [comment]
Since alwaysIdentifier` doesn't exist now and the Max Depth Handler is only a [function ](https://symfony.com/blog/new-in-symfony-4-1-serializer-improvements) and there is no parameter, how can we solve this problem ?

**Comment by pierre-H** [comment]
For history : 
@dunglas Added alwaysIdentifier which was a great feature : #1528 
Then @dunglar reverted in #1696 for https://github.com/symfony/symfony/pull/26108 but it was closed and we don't know what to do ...

**Comment by silverbackdan** [comment]
You may be looking for
https://symfony.com/blog/new-in-symfony-4-1-serializer-improvements#added-a-maxdepth-handler

It can be implemented now with the latest Symfony Serializer.

**Comment by pierre-H** [comment]
Yes but the question is how do I add it to AP ?

**Comment by silverbackdan** [comment]
Write a custom normalizer
https://api-platform.com/docs/core/content-negotiation/#writing-a-custom-normalizer

and include the handler
```
$normalizer->setMaxDepthHandler(function ($foo) {
    return '/foos/'.$foo->id;
});
```

**Comment by pierre-H** [comment]
Ok, thanks @silverbackdan

**Comment by silverbackdan** [comment]
@pierre-H No problem, happy to help!

**Comment by silverbackdan** [comment]
Also, For a generic example to get the IRI you may want to inject the IriConverter class https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/IriConverter.php
```
```
...
use ApiPlatform\Core\Bridge\Symfony\Routing\IriConverter;
...

public function __construct(IriConverter $iriConverter)
{
    ...
    $this->iriConverter = $iriConverter;
    $normalizer->setMaxDepthHandler(function ($foo) {
        return $this->iriConverter->getIriFromItem($foo);
    });
}
```

Very rough just to give you and others a general idea but hopefully you get the gist.

**Comment by ghettovoice** [comment]
Hi for all!
Is the last solution with `setMaxDepthHandler` still actual?
I tried it but with no luck. The handler gets array instead of object as first argument, obviously due to `maxDepthHandler` invoked after relation normalization:
 - invoking of the `setMaxDepthHandler` https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L99
- `getAttributeValue` implementation from `AbstractItemNormalizer` returnes normalized relation as array https://github.com/api-platform/core/blob/master/src/Serializer/AbstractItemNormalizer.php#L389

As a result: I can't use `$iriConverter->getIriFromItem($object)` because it expected resource object.

Also I have an issue with `maxDepth`, I want set it to `1` (to get `parent` from example above as IRI on the first level) but it doesn't work because the first invocation of `isMaxDepthReached` always returns `false`. https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L423. Maybe this should be asked on the symfony main repository, I just want to know is relevant or I'm doing something wrong.
Thanks!
