### ISSUE TITLE
List of services not sorted alphabetically in new swagger

### ISSUE THREAD

**Issue by mcanepa** [api-platform/core#1320]
In 2.0.9 the list of available services appeared in alphabelitcal order, but in 2.1.0 beta2 the same list it is not in the correct order.

**Comment by meyerbaptiste** [comment]
What do you call "services"?

**Comment by komik966** [comment]
I think that "services" here means "api endpoints". Actually, latest versions of api-platform don't support alphabetical sorting of endpoints in swagger doc.
I'm sure that update of swagger-ui will solve the problem, because they introduced filtering support https://github.com/swagger-api/swagger-ui/pull/3196

**Comment by mcanepa** [comment]
Sorry for the miswording. @komik966 is right, I'm talking about "api endpoints". They were used to appear in order, but now they don't.

**Comment by mcanepa** [comment]
This looks solved in 2.1.0
