### ISSUE TITLE
ACL support

### ISSUE THREAD

**Issue by felicitus** [api-platform/core#145]
Does DunglasApiBundle has support for ACLs? As far as I understood the Sf2 ACL documentation one must implement this in code rather than by configuration.

**Comment by dunglas** [comment]
There is nothing special regarding ACL in API platform but using ACL from the security component works.

However using roles is preferred over using the ACL component (it is in the process of being extracted from the core of Symfony).

**Comment by felicitus** [comment]
The question is rather if the Actions like `GetCollectionAction`, `GetItemAction` and `DeleteItemAction` somehow respect ACLs for items or if one needs to implement this.

I'm wondering if I should extend the default actions to include ACL checking.

**Comment by ogizanagi** [comment]
After beta3, you'll be able to define a `kernel.view` listener yourself (the same way it works for a custom [Responder](https://github.com/dunglas/DunglasApiBundle/blob/v2-metadata/Resources/doc/content-negotiation.md#creating-a-responder), right before the `ValidationViewListener` which would be able to handle this kind of checks.

It's pretty simple to expose a configuration for this listener in order to set different security checks according to the resources and actions.

**Comment by felicitus** [comment]
That sounds excellent! I'll leave this issue open so that I can contribute some documentation regarding ACLs.

**Comment by dtomasi** [comment]
I also like to implement a kind of Access Control, but I don´t think that this is a good solution to check if a User/Token is granted. Could´d you dispatch a Event in `ResourceController`,  which allows to check quickly if the Resource is accessible for the current user?? At this point I also tried to add a EventListener as @ogizanagi described in his post above, but if I register the event on `kernel.view`, the expensive work on the Controller´s action is done before I can authorize the User. And if I register the Event on `kernel.controller`-Event I need to load all the resources twice to Check if the user is authorized ... 

Would´t it be easier if every action in `ResourceController` dispatches a `isGranted`-Event ???

Best regards Dominik

**Comment by ogizanagi** [comment]
@dtomasi : 

>  At this point I also tried to add a EventListener as @ogizanagi described in his post above, but if I register the event on kernel.view, the expensive work on the Controller´s action is done before I can authorize the User. 

There is nothing expensive in the controller at all, as it only retrieve the current object on which you'll probably vote for.

> Would´t it be easier if every action in ResourceController dispatches a isGranted-Event ???

That might be the point: I was talking about 2.0 where the `ResourceController` does not exist anymore in favor of the ADR patterns and [actions](https://github.com/dunglas/DunglasApiBundle/tree/master/Action), not 1.0.

Using 1.0, you have some handful events like [Events::RETRIEVE](https://github.com/dunglas/DunglasApiBundle/blob/1.0/Controller/ResourceController.php#L218) which might be similar.

**Comment by ogizanagi** [comment]
Also, using 2.0, if you don't want to vote on the object, but only on the resource type and avoid the controller to do extra work, you might want to use a `kernel.request/controller` event and [the `_resource_type` request attribute](https://github.com/dunglas/DunglasApiBundle/blob/master/EventListener/ResourceTypeRequestListener.php#L53).

In 1.0, you can do the same thing based on the `resource` attribute and retrieving the resource type from it in your listener.

You certainly have tried this regarding your comment:
> if I register the Event on kernel.controller-Event I need to load all the resources twice to Check if the user is authorized 

but could you give us more explanations about the issues you encountered with it ?

**Comment by dtomasi** [comment]
I will try...  but your response is just to fast ... ;-)

**Comment by dtomasi** [comment]
When is a release of 2.0 planed??

**Comment by dunglas** [comment]
Not yet... Probably at the end of 2016. It's already usable right now but BC break will be introduced.

**Comment by dunglas** [comment]
Start of 2016 sorry.

**Comment by dtomasi** [comment]
Let´s get back to my Problem ... 

I´d like to use Symfony´s ACL ... But this is not so easy with the current 1.0 ... I created a EventSubscriber that listens to `kernel.controller` because I don´t want do do the authorization after the Controller was invoked ... On `kernel.controller` I would do the check it the User is granted and need to load the Resources in this Subscriber. For setup the ACE I need to register all other post events to make sure the correct ACE is set. 

This is the reason why I would recommend to have a `isGranted`-Event in every Controller-Action ... 

I´m talking only about 1.0 ... Is there a Chance to implement Events that can handle this ??

**Comment by Simperfit** [comment]
@dtomasi and now with api-platform V2 ?

**Comment by Simperfit** [comment]
@dunglas This can be closed, since there is #583 ?
