### ISSUE TITLE
Expose No Resource

### ISSUE THREAD

**Issue by guiyomh** [api-platform/core#1465]
hi all,
I ask my question, because I have not really been answered.
i have an object with an logical. This object is not an entity, because it’s a set of tools. And i would like expose it throught the api. What is the best way with the api-plateform ?

below, an exmple of class.

```php
<?php

declare(strict_types=1);

namespace AppBundle\Model;

class Calculator
{
    /**
     *
     * @param int[] $ints
     *
     * @return int
     */
    public function sum(array $ints): int
    {
        return array_sum($ints);
    }

    /**
     *
     * @param int $int1
     * @param int $int2
     *
     * @return int
     */
    public function diff(int $int1, int $int2): int
    {
        return $int1 - $int2;
    }

}
```

**Comment by ymarillet** [comment]
This is a non-sense in term of REST

http://restful-api-design.readthedocs.io/en/latest/resources.html

**Comment by soyuka** [comment]
You could aggregate data in a service though.

**Comment by ymarillet** [comment]
But a service should not have an exposed data state, otherwise it's a poor choice of design (breaking single responsibility)

**Comment by ymarillet** [comment]
If "service" has the Symfony (or "code" ... don't know how I could say it better) meaning ...

**Comment by soyuka** [comment]
This is valid to me as well:

```
class Entity {
  public $foos;
  
  /**
   * @ApiProperty()
   */ 
  public getComputation() {
      return array_sum($foos);
  }
}
```

By service I meant that you can do something like:

```
class Entity {
  public $computations;
}

class DataProvider implements DataProviderInterface {
   public function getCollection() {
       // use data from anywhere, can be php class, can be a dbms etc.
       $data = new Entity();
       $data->computations = rand();
       return [$data];
   }
}
```

**Comment by guiyomh** [comment]
@soyuka i'll test that. thx

**Comment by ymarillet** [comment]
For me, there are 2 kinds of objects.

1) objects that encapsulates data
2) objects that manipulates data

An object should never do both.
An Entity, a Value Object, a DTO, etc., belongs to the first category
A service belongs to the second category

In your example @soyuka , the objects of the class "Entity" belongs to the first category.
The DataProvider ones belongs of course to the second.
@guiyomh 's Calculator are objects of the second category as well.

In term of REST, you can only expose the objects of the first category (those that can be called Resource) because they DO have a state of data, a business meaning, where you can apply a whole bunch of methods on, that can modify their content.

You cannot modify anything substantial on a service thought, it's just a rail of logic. The basic SF controllers are perfect for that, so it does not belong to the REST world, but to the RPC world. You could of course expose operations that will use these services, but you still need a resource for that.

What @guiyomh is trying to achieve in fact is to map RPC operations inside the API documentation (the swaggerish interface, hydra contexts, etc.), but to me it's like mixing a lemon with an egg, it won't taste very good ...

**Comment by backbone87** [comment]
But hydra and swagger are very capable of handling such RPC style things, so why not facilitate ApiPlatform for it?

Nowhere is mentioned that ApiPlatform does/should/would only support REST and nothing else.

just as a side note: i always wondered how `POST /collection` fit into the pure REST worlds view

**Comment by guiyomh** [comment]
I agree with your vision @ymarillet . I need to make an API over an existing SI. I have 90% of the objects/models that go into REST and I have some that do not fit your ideal world. 

**What do I do** ? 
I give up Api-Platform and do something from scratch? 
Or am I watching if Api-Platform allows me to answer the specific 10% of my client?

I chose to follow on api-platform, and tomorrow to offer my client a standardization of his IS for stuff not very consistent. But my priority for the moment is to do the work I have been entrusted with, and not to fart the SI of my client. That's why I asked this question that seems to you stupid.

**Comment by ymarillet** [comment]
All projects have edge cases, but you can't expect open source to resolve them for you. I am not saying ApiPlatform should stay resource-centric, I am saying that it currently IS resource-centric, so if you want to use ApiPlatform in its current state, you should make your customs operations on (a) specific resource(s).

I believe what you want to achieve will create or modify data, so you can make this data a resource ( with a custom data provider that could use subrequests for example, etc.), so you can benefit from all ApiPlatform's automatisms (including api doc).

Otherwise as I stated before, it's perfectly possible to achieve your goals with classic controllers/actions, and you could override the documentation templates to add whatever you want.

**Comment by sroze** [comment]
> What @guiyomh is trying to achieve in fact is to map RPC operations inside the API documentation (the swaggerish interface, hydra contexts, etc.), but to me it's like mixing a lemon with an egg, it won't taste very good ...

@ymarillet I'm thinking the other way around. RPC is a very nice way of designing APIs and have a lot of advantages. I don't mean this should replace (this blurry name that is) REST.

> Otherwise as I stated before, it's perfectly possible to achieve your goals with classic controllers/actions, and you could override the documentation templates to add whatever you want.

Exactly. @guiyomh, let's try to help you not to fart on your client, that's not very nice. In order to help you as much as possible, can you give us what is the expected outcome of your API? You have copy/pasted a PHP class doing some things... how do you want it to be "used" via the API? Are you willing to sacrifice some features or not (i.e. what are the **mandatory** features for this endpoint) ?

**Comment by Simperfit** [comment]
Closing as we didn't get any feedback, feel free to re-open or ping me if you have more information.
