### ISSUE TITLE
underscore in field name does not work with @Groups

### ISSUE THREAD

**Issue by hariszukanovic** [api-platform/core#1554]
I am using doctrine.orm.naming_strategy.underscore, in generated entities, the member variables are named in snake case. 
When using `@Groups` to select fields, any of the fields with an underscore in their name are missing from the response. 
Example: service_index
Any fields that are a single word (no underscore) do not exhibit this problem.
Also, when not using `@Groups` everything works just fine.

If variables are named in camel case, they appear in the response even when using `@Groups` and even if the column in the DB is still named in snake case.
Example: serviceIndex

v2.0.11 and v.2.1.4 tested.

**Comment by hariszukanovic** [comment]
Am I the only one using underscores :) ?
Can anyone please confirm this is a known problem?

**Comment by colinedmz** [comment]
@hariszukanovic : I have the same problem

**Comment by netsuo** [comment]
@hariszukanovic  I have the same problem and it even weirder.

Suppose you have a field name `entity_id`. With `@groups`, as you stated, it is not returned.

Now, do this:

```
    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $entity_id;


    /**
     * @Groups("get")
     * @var int
     */
    private $entityId;
```

Notice I just duplicated the variable and set the second camelCase one to `@groups` and removed the group on the first.

**Result**: your variable is on the api response named like the second variable even though the colum `getter` is still on the snake_case one

```
{
  "@context": "/contexts/Test",
  "@id": "/tests",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/tests/1",
      "@type": "Test",
      "entityId": 1871912
   }
}
```

**Comment by rubiodamian** [comment]
Same to me. Super weird bug.

**Comment by hariszukanovic** [comment]
Should this be fixed in the next version?

**Comment by Simperfit** [comment]
Could you please provide a little project based on https://github.com/api-platform/api-platform in order to test this behaviour ?

**Comment by rubiodamian** [comment]
@Simperfit  if any field of the ApiResource entity has an underscore "_" the field will be ReadOnly. Is simple as that.

**Comment by teohhanhui** [comment]
I suspect this has to do with how the Symfony PropertyInfo component extracts accessor and mutator methods, specifically:

https://github.com/symfony/symfony/blob/v4.1.0/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L287

https://github.com/symfony/symfony/blob/v4.1.0/src/Symfony/Component/PropertyInfo/Extractor/ReflectionExtractor.php#L320

If your property name does not follow the convention, you'd have to add the missing property metadata yourself.

**Comment by hariszukanovic** [comment]
Would you have a working example of this (should I call it workaround?)?

**Comment by Cethy** [comment]
I have the same problematic behavior w/ fields prefixed with `is*` (like `isActive`) : 
- the `@Groups` does not work (field doesn't show in the response) ;
- Swagger correctly displays the expected documentation ;
- but when group strategy removed, it shows as a field name `active` in the response ;

If you remove the group strat too, I guess you'll see your field camelized.

**Comment by soyuka** [comment]
closing, use custom metadata if the behavior differs from the one expected by the property info as @teohhanhui said

**Comment by erikkubica** [comment]
Even weirder behaviour is that if it´s camel case, api platform returns array of  IRIs if its snake case it returs list of objects in some places and in some scenarios and in some it returns objects. My project takes like 2x longer with api platform than without it. Took my few hours to figure out the underscore thing, fixed part of my code, but broke the other part. So i have no idea what to do.

**Comment by dobrescucristian** [comment]
I'm not sure what the "custom metadata" solutions refers to, that only lead me to SQL errors because the DB columns are still "some_thing" and setting the name property in @ORM\Column to "someThing" broke the queries.

But if you find this issue on google because you're naming your Entity properties "some_thing" and they don't show in your API responses, it's because you need to name them "someThing".

If you want "some_thing" in the the API response, do this:

![image](https://user-images.githubusercontent.com/3964102/90144357-64d18e80-dd87-11ea-9a57-61325cba3624.png)

From the docs: https://api-platform.com/docs/core/serialization/#name-conversion

**Comment by TeLiXj** [comment]
Using camel case in variables only is mandatory to develop Symfony bundles or help in the Symfony project. If your project follow PSR-12 (PSR-2 is deprecated) you can choose what do you want for variable names. I always choose snake case and have use a lot of different bundles without problems since Symfony 2, and reflection works fine in all cases.
I don't know how this issue can be closed saying "if the behavior differs from the one expected by the property info" because is a completely correct way to define a entity in Symfony and Doctrine. I hope that you can reconsider your action and try to fix it.
Meanwhile, if you have this problem you can use the groups directly in the setters o getters involved.
You must change from
```php
/**
 * @ORM\Column(type="int")
 * @Groups({"baz:read", "baz:write"})
 */
private $foo_bar;
```
to
```php
/**
 * @ORM\Column(type="int")
 */
private $foo_bar;

/**
 * @Groups({"baz:read"})
 */
public function getFooBar(): ?int
{
    return $this->foo_bar;
}

/**
 * @Groups({"baz:write"})
 */
public function setFooBar(int $foo_bar): self
{
    $this->foo_bar = $foo_bar;

    return $this;
}
   ```

**Comment by evotodi** [comment]
By the way another workaround is a modification to @TeLiXj  answer because for me rewriting annotations for 207 properties plus getters and setters was looking like a chore.

```
/**
* @ORM\Column(type="boolean")
* @Groups({"dataspec:read","dataspec:write"})
*/
private bool $g_heEn = true;
```

Changed getters and setters from:

```
public function isGHeEn(): bool
{
	return $this->g_heEn;
}

public function setGHeEn(bool $g_heEn): self
{
	$this->g_heEn = $g_heEn;
	return $this;
}
```

To _(notice the underscore placement)_:

```
public function isG_HeEn(): bool
{
	return $this->g_heEn;
}

public function setG_HeEn(bool $g_heEn): self
{
	$this->g_heEn = $g_heEn;
	return $this;
}
```

And then docs post example shows:

```
{
  "g_heEn": true
}
```

And return example shows:
```
{
  "g_heEn": true,
}
```

Which is what i was after.
Yes it is not PSR-12 or PSR-2 and it is snakeCamel but when in a pinch.

**Comment by TeLiXj** [comment]
Finally, after update to PHP 8 and move from annotations to attributes all works fine!
