### ISSUE TITLE
NelmioApiDoc parser location

### ISSUE THREAD

**Issue by mRoca** [api-platform/core#156]
Hello, I have a simple question: why put the Nelmio documentation extractors in the NelmioApiDocBundle ? I don't think that the DunglasApiBundle specific PR have a place in the source code of the Nelmio project, what do you think of it ?

For example, I want to create this PR : https://github.com/nelmio/NelmioApiDocBundle/compare/master...mRoca:feature/dunglas-avoid-infinite-recursion , and I would like to add some tests to prevent infinite recursion with circular entities relations with the same serializer groups. As this items are DunglasApiBundle specific, add them in the NelmioApiDocBundle doesn't seem normal.

Other example with this potential PR (wip) : https://github.com/nelmio/NelmioApiDocBundle/compare/master...mRoca:feature/dunglas-add-max-depth . In order to add a default MAX_DEPTH option in the Nelmio doc, I would like to add a config option, or something like it.

**Comment by ogizanagi** [comment]
I also wondered this a while ago, and there is only something which could be problematic, I think: 
How will the DunglasApiBundle tests the NelmioApiDocBundle behavior if tests should also belong to this bundle ?

This means the DunglasApiBundle should have a dependency on `nelmio/api-doc-bundle` for tests and replicate a big part of what is done in the bundle ?

**Comment by dunglas** [comment]
@ogizanagi yes it's exactly why I've opened the PR on NelmioApiDoc initially. On another hand, I've no problem having NelmioApiDoc in the `require-dev` section of this bundle.

**Comment by ogizanagi** [comment]
Then we have our answer :smile: 

How would you proceed if some features targeting the nelmio api doc behavior requires some configuration ?
Will you put this config in the DunglasApiBundle ?

**Comment by ogizanagi** [comment]
I feel like the fact Nelmio related stuff is located in another bundle is quite a big issue, especially until the api bundle has its first stable release (For instance, the `dev-master` is now broken due to the move of mapping interfaces). I don't think we should have another BC break factor.

I think the nelmio related stuff should move back into the bundle. It could be required in `dev` only, or added by Travis on build. Tests could also be marked by a dedicated group in order to exclude them when executing tests locally.

**Comment by teohhanhui** [comment]
Fixed by #410
