### ISSUE TITLE
Question: How to deal with complex SQL query

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#1626]
Hello.

In my app, I have some "complex" queries and I don't really know how to integrate them with API Platform.
I have tried 2 different ways, but the 2 solutions are not perfect.

For now, I will talk about `item` and not `collection`. But actually, it's almost the same ;)

### Using an extension

Because API Platform automatically applies some join thanks to `EagerLoadingExtension` it really mess up my query and give me wrong results. 
I have tried 2 different things: 

1. set my extension before the EagerLoading: I get more result to extra "left join"
2. set my extension after: I had to call `$qb->resetDQLParts();` ouch

### Using a custom DataProvider

Actually, It does the job, but it seems not really natural to me. for the collection, I'm loosing many advantage like the pagination & all.

---

What is the best way to achieve that?

I saw we can disable the eager-loading. This looks the best idea IMHO, but before doing that, I wanted to be sure what I'm loosing. BTW, we don't you disable this feature by default ? because it could lead to many troubles isn't ?

**Comment by soyuka** [comment]
Just use the extensions you want! 

I'm doing this a lot:

1. Create a DataProvider
2. Inject Extensions manually (not by using a collection), see https://github.com/api-platform/core/pull/1557/files for recent aliases so that Autowiring works
3. At the end  just apply the extensions you want manually (for example the FilterExtension) as we're doing [here](https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L92)

If you're doing a native / manual query you don't need EagerLoadingExtension (nor FilterEagerLoadingExtension) because you would probably join manually all your relations.

We don't disable it by default because it has a huge performance impact when relations are serialized.

**Comment by lyrixx** [comment]
Ok thanks for you quick and nice answer.

I was thinking the same (about using custom data provider + extension provided by API Platform). But I thought it was too "hacky" to do that, and not so natural. However I don't know why ;)

Just one last question before closing this issue: There are no way to disable for few endpoint the EagerLoadingExtension /  FilterEagerLoadingExtension), isn't ?

**Comment by soyuka** [comment]
> Just one last question before closing this issue: There are no way to disable for few endpoint the EagerLoadingExtension / FilterEagerLoadingExtension), isn't ?

There is, just disable eager loading at the operation level [see here](https://api-platform.com/docs/core/performance/#override-at-resource-and-operation-level).

>  But I thought it was too "hacky" to do that

Not hacky, those are meant to be used if you need too :).

**Comment by lyrixx** [comment]
Thanks. Good weekend
