### ISSUE TITLE
Strange behavior with relation and validation

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#1641]
When there is a relation, and When I post something the behavior of API Platform is not always the same.

## Case 1: Missing property

```json
{
	"@context": "\/app_dev.php\/v2\/contexts\/ConstraintViolationList",
	"@type": "ConstraintViolationList",
	"hydra:title": "An error occurred",
	"hydra:description": "organization: This value should not be blank.",
	"violations": [
		{
			"propertyPath": "organization",
			"message": "This value should not be blank."
		}
	]
}
```

It's perfect :white_check_mark: 

## Case 2: The property is here, but malformed (or the ID does not exist anymore):

```json
{
	"@context": "\/app_dev.php\/v2\/contexts\/Error",
	"@type": "hydra:Error",
	"hydra:title": "An error occurred",
	"hydra:description": "Expected IRI or nested document for attribute \"organization\", \"string\" given."
}
```

IMHO, this is wrong, I would expect something like this:

```json
{
	"@context": "\/app_dev.php\/v2\/contexts\/ConstraintViolationList",
	"@type": "ConstraintViolationList",
	"hydra:title": "An error occurred",
	"hydra:description": "organization: This value should not be blank.",
	"violations": [
		{
			"propertyPath": "organization",
			"message": "This value can not be found."
		}
	]
}
```

**Comment by dunglas** [comment]
It's because the sanity check doesn't occur at the same level. The "case 2" exception is thrown directly by the denormalizer because the provided document is not a valid JSON-LD one. Just as if your JSON document contains a syntax error, or a type error (when you put a string in a property that must contain a number for instance).

As rule of thumb, the `violations` key is a proprietary extension provided by API Platform, but is not part of the Hydra spec (it's valid to add custom properties). There is no guarantee that this key will be present, a client should always failback to the `hydra:description` property if there is no `violations`.

**Comment by lyrixx** [comment]
> It's because the sanity check doesn't occur at the same level. The "case 2" exception is thrown directly by the denormalizer because the provided document is not a valid JSON-LD one. Just as if your JSON document contains a syntax error, or a type error (when you put a string in a property that must contain a number for instance).

Yes I know ;)

> As rule of thumb, the violations key is a proprietary extension provided by API Platform, but is not part of the Hydra spec (it's valid to add custom properties). There is no guarantee that this key will be present, a client should always failback to the hydra:description property if there is no violations.

Ah OK. I did not know that. 

So I think we can close this issue
