### ISSUE TITLE
Cant update elem

### ISSUE THREAD

**Issue by marcinbis92** [api-platform/core#1659]
Hi, I have problem with update my elem
response:
`"Expected IRI or nested document for attribute \"us\", \"string\" given."`
thanks for help

**Comment by Nek-** [comment]
Hello,

Please notice this is **NOT** a forum but an issue tracker for the project. Please consider avoiding this kind of message in Github issues.

Also your problem is not well described so nobody is susceptible to help you.

Please close this issue and try to get support on [StackOverflow](https://stackoverflow.com/) or [Slack](https://symfony.com/slack-invite), that's why these tools are designed for (you may also use [some search tool](http://www.lmgtfy.com/?q=Expected+IRI+or+nested+document+for+attribute+%5C%22us%5C%22%2C+%5C%22string%5C%22+given.) to get your answer). Thanks.

**Comment by soyuka** [comment]
> "Expected IRI or nested document for attribute \"us\", \"string\" given."

You have send a bad formatted data. Please give more detailed informations about what you're trying to do.

**Comment by marcinbis92** [comment]
@soyuka 
I use this docs https://api-platform.com/docs/admin/handling-relations-to-collections
with same entity Person & Book
<img width="601" alt="zrzut ekranu 2018-01-19 o 15 41 14" src="https://user-images.githubusercontent.com/35339189/35155849-445bbb02-fd2f-11e7-85ec-bfd761163a07.png">
<img width="1579" alt="zrzut ekranu 2018-01-19 o 15 41 28" src="https://user-images.githubusercontent.com/35339189/35155850-44779fde-fd2f-11e7-8075-74b0ab73bdf2.png">
<img width="207" alt="zrzut ekranu 2018-01-19 o 15 41 40" src="https://user-images.githubusercontent.com/35339189/35155851-4498c268-fd2f-11e7-9664-6f54c2e44791.png">

**Comment by Simperfit** [comment]
If you still have an issue please open one on the https://github.com/api-platform/admin component, this seems not linked to core, thanks!
