### ISSUE TITLE
[RFC] Add a where filter.

### ISSUE THREAD

**Issue by Simperfit** [api-platform/core#1832]
@dunglas on https://github.com/api-platform/api-platform/issues/577:
```
The best would be to have something like this: https://loopback.io/doc/en/lb2/Where-filter.html
A or filter on steroid!
```

This will give the ability to filter everything like a dql or a sql where.

**Comment by Simperfit** [comment]
is this really needed ? I mean we already have alots of filter covering alot of the uses cases of the where filter. Could we maybe reuse the filter we already have with this one like a proxy ? or do we want to implement everything and then deprecate the other filter ?

**Comment by sstok** [comment]
I think this can be easily solved using the solution I discussed in #991 😛 there are some issues reported in the RollerworksSearch repository. But I haven't had time to use the API-Platform yet, so any suggestions on how to do this better are welcome (including a completely new approach) for search processing with the API-Platform)). https://github.com/rollerworks/search/issues/174

I need some good key points to work-on because I don't have a fully functioning project atm and guessing hasn't brought my anything good in the past 🤦‍♂️

**Comment by meyerbaptiste** [comment]
@theofidry did it https://github.com/theofidry/LoopBackApiBundle/blob/master/src/Resources/doc/where-filter.md#example-2 😄

**Comment by teohhanhui** [comment]
I'm definitely -1 for this. This opens a whole can of worms.

**Comment by soyuka** [comment]
Also -1

**Comment by Simperfit** [comment]
@sstok I will try to look at it when I can ;).

Closing as this seems to be not needed :).
