### ISSUE TITLE
GraphQL broke after some commit

### ISSUE THREAD

**Issue by KriBetko** [api-platform/core#1880]
Hi. I'm wanted to check new feature for GraphQL with filters for nested property (#1868) but if i'm require on composer this commit (c1395866e8b564d27d51c9adeff1183ccc0575f9) i got "500 Internal Server Error" for any POST request on "api_graphql_entrypoint" without errors on log or profiler. 
I checked and this occurs after 2e0c64769e2472cf3bc50d19d2614b5caab0dcd0 commit (on previous b54979b9464cfa5c14022959a374fe280e619dd9 commit all is OK).

I'm not sure that I understand everything correctly, so I ask for help in solving this problem

**Comment by antograssiot** [comment]
This PR was only merge in 2.2 branch but not in master. Are you sure you where not using the master branche before ?

**Comment by antograssiot** [comment]
So I've been digging quickly into it and the addition on filtering for nested entity is not the root cause, it seems that introspection is broken since `InputUnionType` usage addition in the SchemaBuilder https://github.com/api-platform/core/compare/v2.2.5...d805e9a#diff-b7cf573372ef33efd3ea514a70783519L344

There are discussions already in https://github.com/api-platform/core/pull/1858 and they are trying to fix this upstream

**Comment by alanpoulain** [comment]
The issue is only with introspection and it shouldn't affect the requests.
I was hoping a quick fix in graphql-php but it doesn't seem to happen soon so I will propose a dirty way to fix it soon.
