### ISSUE TITLE
GraphQL Validation?

### ISSUE THREAD

**Issue by bwegrzyn** [api-platform/core#1893]
Do GraphQL mutations support validation? It seems as though the ValidateListener is not called on  mutations and as a consequence my PRE_VALIDATE event listener is not being called. Symfony reports that the ApiPlatform\Core\Validator\EventListener\ValidateListener listener is not called.

This seems to work fine with regular REST calls, but not GraphQL.

**Comment by dunglas** [comment]
Yes, the validator is called: https://github.com/api-platform/core/blob/master/src/GraphQl/Resolver/Factory/ItemMutationResolverFactory.php#L124

The listener is not called (no listener are called) because it works differently for GraphQL (the validator service is called directly), listeners are for REST only.

**Comment by bwegrzyn** [comment]
I see... I suppose that makes sense. Thanks!
