### ISSUE TITLE
[GraphQL] One-to-Many relations?

### ISSUE THREAD

**Issue by bwegrzyn** [api-platform/core#1964]
When defining a one-to-many relation (ex. User->Vehicles), GraphQL currently expects `[String]` on the create/update mutation. Is there a way to create new Vehicles in the same request as creating/updating the User? It seems like GraphQL expects you to pass a list of Vehicle IDs instead of an array of Vehicle data like I would do in a REST call. 

I would like to avoid doing multiple API calls if possible. Any ideas on how to accomplish this?

**Comment by alanpoulain** [comment]
It was possible before, but was removed because it was causing some issues with the introspection.
Everything is explained here: https://github.com/api-platform/core/pull/1886.

**Comment by bwegrzyn** [comment]
I see... so it seems like this feature won't be returning until Facebook agrees on the spec for it.

@alanpoulain Until the spec is agreed upon, what is the recommended approach to working with one-to-many data structures?

**Comment by alanpoulain** [comment]
Yes or if the schema builder generates two fields. One for the IRI and the other for the data.
Unfortunately, you need more than one request to make it work with the current implementation.

**Comment by oleg-brizy** [comment]
I made it work like this https://github.com/api-platform/core/issues/3422

**Comment by jnugh** [comment]
I think having two fields is not the best solution in every case. This becomes an issue when a field may not be null. The client would then have to fill both fields which does not make sense. Alternatively both fields are nullable which makes it harder to interpret the schema and would allow invalid input data that "looks right".

How about adding a temporary, user generated id that can be used to identify an object after it has been created?

When the client adds such a temporary id to a create mutation and uses the same id as a reference later in the same request it would refer to the newly created entity.
I just implemented this pattern because we would like to be able to create multiple related entities in the same transaction and it works quite well.

```graphql
mutation {
  createFoo(input: { tmpId: "myAwesomeObject", name: "test" }) {
    foo {
      id
      name
    }
  }
  createBar(input: { foo: "myAwesomeObject", name: "test2" }) {
    bar {
      id
      name
      foo {
        id
        name
      }
    }
  }
}

```

would return something like:
```json
{
  "createFoo": {
    "foo": {
      "id": "/api/foo/1",
      "name": "test"
    }
  },
  "createBar": {
    "bar": {
      "id": "/api/bar/1",
      "name": "test2",
      "foo": {
        "id": "/api/foo/1",
        "name": "test"
      }
    }
  }
}
```

The temporary id can be stored throughout the request, along with the entity class name and the newly persisted entity.

**Comment by alanpoulain** [comment]
See https://api-platform.com/docs/main/core/graphql/#embedded-relation-input-creation-of-relation-in-mutation for a way to solve this issue.
