### ISSUE TITLE
Subresource not found resulting in a code 200?

### ISSUE THREAD

**Issue by lvillarino** [api-platform/core#2008]
Hello,

I think that this pull request https://github.com/api-platform/core/pull/1819 was merged wrong.

Lastest Version: https://github.com/api-platform/core/blob/v2.2.7/src/EventListener/ReadListener.php
Pull Request: https://github.com/Simperfit/core/blob/a65e09e354df3f5f408234e0cf8eb1e4b3bbd18b/tests/EventListener/ReadListenerTest.php

Thanks

**Comment by soyuka** [comment]
Mhh but if it's a subresource collection and it's empty the behavior is the same as with collection operations, it just returns an empty array. If it's an item subresource, it'll end up being 404 which is what we expect.

**Comment by lvillarino** [comment]
the system is returning 200 when it is an empty subresource and the ideal code is 404.

**Comment by soyuka** [comment]
Not if it's a collection subresource :). 

You have 2 kind of subresources, the one with an ending param (`/foo/:id/sub/:param` - item subresource) which will end in a 404 if nothing matches. Then, you have the collection subresource (`/foo/:id/sub`) which will be an empty collection.

**Comment by mab05k** [comment]
What about in the situation where the parent of the subresource does not exist? To use the collection subresource example: `/foo/:id/sub`, what if the provided ":id" does not exist in the database?

**Comment by soyuka** [comment]
> What about in the situation where the parent of the subresource does not exist? To use the collection subresource example: /foo/:id/sub, what if the provided ":id" does not exist in the database?

This should definitely be a 404.

**Comment by soyuka** [comment]
> What about in the situation where the parent of the subresource does not exist? To use the collection subresource example: /foo/:id/sub, what if the provided ":id" does not exist in the database?

So I've though a bit more about the issue and it'd be too complicate to implement this behavior, especially that I don't see any real benefits.

To recapitulate:
- `404` will occur ONLY in the case of an `item` subresource, meaning it is a `toOne` relation and that the relation (or any previous relation in the subresource url) has not been found.
- `200` will occur for every other case, where a `collection` is expected because this is the behavior of collection operations to return an empty array. There is no way to know which part of the subresource was not found unless we issue more queries.

By parts I mean that for `/foo/:id_foo/bar/:id_bar/foobar` it's hard to know if `foo` and/or `bar` wasn't found or if it's just an empty collection of `foobar`.
