### ISSUE TITLE
The Swagger doc misses the JSON-LD schemas

### ISSUE THREAD

**Issue by guillaume-perreal** [api-platform/core#2035]
I am using swagger-codegen to generate TypeScript interfaces from the Swagger documentation, using only the models. It allows me to type-check the objects in the frontend code.

However, only the "simple" (application/json) schema is listed in the Swagger docs. It would be useful to also have the full JSON-LD schemas, so the extra item fields ("@id", ...) and/or the collection schema could be properly generated as well.

**Comment by luca-nardelli** [comment]
I found this issue while I was looking to do the same thing. I've worked around the missing JSON-LD fields by writing a custom decorator for Swagger.

```PHP
<?php

namespace App\Swagger;

use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class SwaggerDecorator implements NormalizerInterface
{
    private $decorated;

    public function __construct(NormalizerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $docs = $this->decorated->normalize($object, $format, $context);

        if (array_key_exists('definitions', $docs)) {
            foreach ($docs['definitions'] as $key => &$def) {
                $def['properties']['@id'] = [
                    'readOnly' => true,
                    'type'     => 'string'
                ];
            }
        }

        return $docs;
    }

    public function supportsNormalization($data, $format = null)
    {
        return $this->decorated->supportsNormalization($data, $format);
    }
}
```

This works assuming you haven't customized the swagger_context with definitions that are not handled by API Platform, otherwise this would add the `@id` field to them as well.

You could probably do something similar to add the collection fields, but you would need to work on the 'paths' part of the $docs object.
