### ISSUE TITLE
Declare the UuidNormalizer service in Symfony bridge ?

### ISSUE THREAD

**Issue by Taluu** [api-platform/core#2077]
It seems the `UuidNormalizer` is not declared, and so the normalizer is not registered and thus never called for an uuid.

This results in an error if your constructor / parameter expects a `Uuid` (or `UuidInterface`).

**Comment by Taluu** [comment]
Nevermind, seems the problem is somewhere else...

**Comment by phpeek** [comment]
@Taluu Sorry for responding here, but I've stumbled upon similar issue. Is there any chance You remember what the problem was ?

I have a public class property marked with:

```php
@var UuidInterface

@ORM\Id
...
```

Unfortunately, this property is never denormalized due to 

> Could not denormalize object of type Ramsey\Uuid\UuidInterface, no supporting normalizer found.

After hours of digging, I've found out that `ApiPlatform\Core\Bridge\RamseyUuid\Identifier\Normalizer\UuidNormalizer` was not even taken into account when determining which normalizer should be responsible for this property.

I see `ApiPlatform\Core\Bridge\RamseyUuid\Identifier\Normalizer\UuidNormalizer` is registered and tagged with `api_platform.identifier.denormalizer`.

The only reasonable solution I was able to come up with is to register this normalizer as a service:

```yaml
services:
    ApiPlatform\Core\Bridge\RamseyUuid\Identifier\Normalizer\UuidNormalizer: ~
```

However, I don't think that's the most elegant solution. Hence me asking for Your findings 😉.

**Comment by Taluu** [comment]
IIRC, it was something along what you found out. So I had indeed to declare the service myself... Can't remember why the service wasn't declared though. :/

**Comment by phpeek** [comment]
Awesome. Thanks for taking time and looking into that again. Cheers !

**Comment by soyuka** [comment]
`UuidNormalizer` is not used as a normalizer, it's only there to decode url parameters that should match an Uuid. About the denormalizer it's weird, what is your code in the getter?

**Comment by Renrhaf** [comment]
I had the same issue with a `UuidInterface` in a constructor.
Declaring the service myself fixed the issue.
