### ISSUE TITLE
Custom operation identifier has a different type from the entity's one but gets normalized with the entity's identifier type.

### ISSUE THREAD

**Issue by blesenechal** [api-platform/core#2116]
I have a GET operation that retrieves an item based on a unique parameter which is a string.
It works fine with 2.2.9, but not with 2.3.0.

It looks like the query parameter value is casted to an int somewhere.

==================================

Example with the api-platform/demo project, to get the books by ISBN

1 - I create a custom operation with "requirements" (as defined in https://api-platform.com/docs/core/operations) :
```
 * @ApiResource(
 *     itemOperations={
 *         "get"={"method"="GET", "path"="/books/{id}"},
 *         "get_by_isbn"={"method"="GET", "path"="/books/by_isbn/{id}", "requirements"={"id"=".+"}},
 *     }
 * )
```

2 - I create a data provider :
```
namespace App\DataProvider;

use ApiPlatform\Core\DataProvider\ItemDataProviderInterface;
use ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface;
use ApiPlatform\Core\Exception\ResourceClassNotSupportedException;
use App\Entity\Book;
use Doctrine\ORM\EntityManagerInterface;

final class BookIsbnItemDataProvider implements ItemDataProviderInterface, RestrictedDataProviderInterface
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function supports(string $resourceClass, string $operationName = null, array $context = []): bool
    {
        return (Book::class === $resourceClass) && ('get_by_isbn' === $operationName);
    }

    public function getItem(string $resourceClass, $identifiers, string $operationName = null, array $context = []): ?BlogPost
    {
        return $this->entityManager->getRepository(Book::class)->findOneBy(['isbn' => $identifiers]);
    }
}
```

3 - When executing the request `GET /books/by_isbn/plop` :
- With 2.2.9 : In `getItem`, `$identifiers` is 'plop' (string)
- With 2.3.0 : In `getItem`, `$identifiers` is 0 (int)

**Comment by soyuka** [comment]
In your parameter route `{$id}` has the type of your resource class `$id` property, which is an integer. Because of this it will go through the identifier [IntegerDenormalizer](https://github.com/api-platform/core/blob/master/src/Identifier/Normalizer/IntegerDenormalizer.php) and transform your string to a number. 
I'm not sure that renaming the identifier would work because of:  https://github.com/api-platform/core/blob/0df20697dcaf9226e8650999b2bf1316e1a92563/src/DataProvider/OperationDataProviderTrait.php#L89

There isn't a good solution for now but I'm looking for one. In the mean time I'd recommend to set `_api_receive` to `false` (avoids the ReadListener) and use your own controller that calls the data provider. 
You could also use a subresource custom collection instead but that's not easy to set up...

----

Side note: 
You could implement the [DenormalizedIdentifiersAwareItemDataProviderInterface](https://github.com/api-platform/core/blob/master/src/DataProvider/DenormalizedIdentifiersAwareItemDataProviderInterface.php). The `$identifiers` will then be an array.

**Comment by blesenechal** [comment]
Thanks for your response.

Note: with your suggestion of using `DenormalizedIdentifiersAwareItemDataProviderInterface`, `$identifiers` is an array but still casted to an int:

```
array(1) {
  ["id"]=>
  int(0)
}
```

**Comment by soyuka** [comment]
Yes I know but it's good to implement that because my fix will probably need it :).

Can you tell me if isbn is a property of your book?

**Comment by blesenechal** [comment]
Yes, isbn is a property of the book (I used the demo project as reproducer)

**Comment by Soullivaneuh** [comment]
You can start a quickfix using `is_numeric` instead of `is_string` inside the `IntegerDenormalizer::support` method.

**Comment by Simperfit** [comment]
This should be considered as a BC Break cc @dunglas.
