### ISSUE TITLE
[GraphQl] [Proposal] Change endCursor behavior in PageInfo

### ISSUE THREAD

**Issue by Reduxx** [api-platform/core#2139]
The endCursor in the PageInfo Object should be the cursor of the last item of the page. It now represents always the last item of the whole collection, which is the last item of the last page.
The desired behavior can be seen in the last example on the [GraphQl-Website](https://graphql.org/learn/pagination/).

I feel like the current behavior has no benefits and makes the endCursor useless for pagination.

If this is somewhat relevant, I will come up with a PR for that :) If not, please elighten me what I'm misunderstanding

**Comment by alanpoulain** [comment]
It seems you're right. There is no specification for it, that's why it has been implemented like this.
See for instance: https://stackoverflow.com/questions/34948295/implementing-startcursor-and-endcursor-in-relay
But since `graphql-relay-js` has implemented it like you explained, it's a good idea IMO to change its behavior. PR welcome ;)
Maybe it should be also interesting to implement backward pagination (with `before` and `last` arguments and `startCursor` field).

**Comment by Reduxx** [comment]
I thought so myself about backward pagination. I can look at this, too :) Maybe I can come up with something working

**Comment by alanpoulain** [comment]
Fixed in 2.4 and backwards pagination in 2.5.
