### ISSUE TITLE
Graphql: can't filter entity collection by ids

### ISSUE THREAD

**Issue by Siregacvek** [api-platform/core#2190]
Hello!

Looks like I found a bug. If I add filter to the entity this way:
```
/**
 * @ApiResource()
 * @ApiFilter(SearchFilter::class, properties={"id": "exact"})
 */
class Entity
```
Then I receive the following schema:
`Entity(first: Int, after: String, id: Int, id_list: [Int])`

When I apply filter by id, it's ignoring and returns me the full collection.
Also I believe that the id must string like `/entities/1` instead of integer.

Or I'm doing something wrong?

**Comment by ArnoudThibaut** [comment]
Hello,

This behavior is quite strange but it's caused by the [normalizeValues function](https://github.com/api-platform/core/blob/b15030beb49bd841e2c788e7d7a818c388c199aa/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php#L370) of the SearchFilter.
With REST operations the values passed to the filter aren't typed and are all strings so there is no problem if you pass to this filter values that are in fact numerical string values.
But with graphQl the values are typed.

For me you have two solutions that depend on your needs :
* First is to use the NumericFilter but this filter doesn't allow to pass multiple values so you won't have the `id_list` argument. (I'm working on it)
* Second is to extends the built-in search filter and override the `normalizeValues` function in order to not discard values that aren't strings.

**Comment by teohhanhui** [comment]
Please do not use the `NumericFilter` for ids

**Comment by teohhanhui** [comment]
I think this type conversion should be handled at the GraphQL layer. As far as the filters are concerned, all values are strings.

**Comment by teohhanhui** [comment]
I think the way to fix this is to introduce the `IriFilter` and deprecate using the `SearchFilter` for IRIs / ids.

Related: https://github.com/api-platform/core/issues/319

**Comment by soyuka** [comment]
LMK if the issue remains after #2277
