### ISSUE TITLE
Question concerning filters and uuid

### ISSUE THREAD

**Issue by rubenvdlinde** [api-platform/core#2281]
Also see https://stackoverflow.com/questions/53001906/api-platform-filters-with-uuid

I can't seem to get filters working with UUID, are filters that are set to exact normilized before being send of to doctrine?

Kind regards

**Comment by soyuka** [comment]
Try to filter on `platform.id` instead of `platform`.

**Comment by rubenvdlinde** [comment]
Nice, that solved the isue! thanxs.
I did however encounter unexpected behavior If we do an api/organisations?platform=/api/platforms/ba8d9958-d8d5-11e8-a9a5-5254007d3b24. Doctrine doesn’t do an inner join and can't correctly decode the UUID but when we do api/organisations?platform.id=ba8d9958-d8d5-11e8-a9a5-5254007d3b24. API platform forces an inner join and then it suddenly works……..

I updated the stack overflow question to reflect this. But my problem is solved for now!

Thanxs a lot!

**Comment by soyuka** [comment]
Maybe because there is some magic involved to transform `relation` to `relation.id` in the Filter when it parses the query. Please stick with `relation.id` (of `relation.bar` if your identifier is named `bar`) it's cleaner and will lead to less mistakes :).

If giving an IRI to the identifier is not supported: 

```
platform.id=/api/platforms/ba8d9958-d8d5-11e8-a9a5-5254007d3b24
```

Please let me know because this should definitively work.

**Comment by soyuka** [comment]
> The only issue with it is of a more theoretical nature and that is that the
join leads to some small performance loss

because it doesn't make an inner join?
