### ISSUE TITLE
[JSON API] (Question) IRI and type seems to break the "type and id pair MUST identify a single, unique resource"

### ISSUE THREAD

**Issue by wildhaber** [api-platform/core#2287]
Hey there,

We are using api-platform with JSON API, and so far we are really happy with it. But unfortunately the actual [ItemNormalizer](https://github.com/api-platform/core/blob/master/src/JsonApi/Serializer/ItemNormalizer.php#L86-L89) for JSON API seems to conflict with the specifications.

So far I have only found issues or open pull request to use plain identifiers instead of IRIs but as far as I understand the specifications, IRIs should not be used in JSON API.

Let's take the example from the [demo](https://demo.api-platform.com/):

```javascript
{
  "data": {
    "id": "/books/18",
    "type": "Book",
    "attributes": { ... },
    "relationships": { ... }
}
```

In terms of identification of a JSON API resource, the specification says:

> Within a given API, each resource object’s **type and id pair MUST identify a single, unique resource**. (The set of URIs controlled by a server, or multiple servers acting as one, constitute an API.)

(see: https://jsonapi.org/format/#document-resource-object-identification)

This can be interpreted differently, but in most of the JSON API consumer (e.g. orbit.js / jsorm etc) this results in an API call like:
```
GET https://example.com/{type}/{id}
# e.g. GET https://example.com/Book/books/18
```

As far as I understand this, a JSON API resource should be serialized to export a resource as follows:

```javascript
{
  "data": {
    "id": "18",
    "type": "books",
    "attributes": { ... },
    "relationships": { ... }
}
```

I can imagine, an argumentation like - `Book/books/18` is a single, and unique resource - this is right but feels a bit odd. But certainly this is the point where I have the main confusion, shouldn't `{type}/{id}` point to an existing resource in terms of a URI as well?

There is a configuration variable `allow_plain_identifiers`, to resolve the part for the `id`, but still results in `Book/18` which points to a `404`.

I'm sure there are different opinions on this topic, but is there a way to override the ItemNormalizer for JSON API to support both?

**Comment by wildhaber** [comment]
Ok, I've mixed up the two different concepts of resources in JSON API's and in the URI's context.

It's all fine as it is :-)

**Comment by maximgubar** [comment]
@wildhaber could you please explain why it is fine as it is ?

atm we are facing same issue, vnd.api+json response from platform looks different from what is taken as an example on https://jsonapi.org/.

from the jsonapi specs it is clear that id and type should be strings, but imho it should be like this in order to do the concatenation with the type to compose a resource url.

also, according to their specs current id make sense to put in the [link.self](https://jsonapi.org/format/#document-resource-object-links)

@soyuka @teohhanhui , tagging you guys here just to get your attention, your opinion is important here. and thanks in advance.
