### ISSUE TITLE
Circular reference in (automatically embedded) non-ressource entities

### ISSUE THREAD

**Issue by remi-blaise** [api-platform/core#2319]
Hello !

While using API Platform today I ran into an issue: 
If you have entity A decorated with `@ApiResource` containing (in my case OneToMany relationship) entity B which is not decorated with `@ApiResource`, then a GET query on entity A ends up throwing a serialization exception: "Circular reference detected".

This happens because API Platform detects entity B is not a ressource and try to embed it with entity A (which is a great idea) but then entity B happens to have a reference toward entity A, which create a circular reference.

I solved it quite easily by defining a normalization group:
```php
use Symfony\Component\Serializer\Annotation as Serializer;

/*
 * @ApiResource(normalizationContext={"groups"={"A"}})
 */
class A 
{
    /**
     * @Serializer\Groups({"A"})
     */
    private $b;
}

class B
{
    /**
     * Don't include in group "A"
     */
    private $a;
}
```

But it would be great to implement it in the framework (which should not be very hard I think).

**Comment by beejaz** [comment]
I had the same problem today but I actually previously had used @ApiResource in entity b and removed it but had'nt removed Asserts & Groups (because I forgot and was lazy) so I was still announcing @Groups and @Assert\ on the properties which caused this. When I removed all those annotations from entity b it didnt throw circular reference error in entity a any more!

Just wanted to say that.

**Comment by soyuka** [comment]
closing as old, feel free to open a new issue if this is still a problem
