### ISSUE TITLE
[GraphQL] Disable collection operations doesn't work

### ISSUE THREAD

**Issue by SCIF** [api-platform/core#2525]
```
/**
 * @ApiResource(
 *     graphql={"query"},
 *     collectionOperations={}
 * )
 */
class User
```

In this case `UsersConnection` still created by `SchemaBuilder`. I assume it's a bug.

**Comment by kiler129** [comment]
I think this will cause BC. Collections are slightly different than relations in GraphQL IMHO.

**Comment by SCIF** [comment]
@kiler129 , what do you mean under relations?

Actual schema looks like:

```
user(id: ID): User
users(first: Int, after: String): UserConnection
```

PR is intended to drop `users` from it.

**Comment by lukasluecke** [comment]
I'm not sure that mixing the "collectionOperations" (which afaik only applies to REST-API atm) and the GraphQL-API is a good idea. I believe that's also what @kiler129 was trying to convey.

It would probably make more sense to modify the `graphql` array of the API-resource config (e.g. split `query` into `query_item` and `query_collection`).

There are several other features that do not apply to the GraphQL-API right now (e.g. @ApiProperty (required, writeable, ..) - see https://github.com/api-platform/api-platform/issues/872

**Comment by SCIF** [comment]
Thanks @lukasluecke for your input. However, I cannot see any point to duplicate settings under the `graphql` branch which is not autocompleted and validated properly. Moreover, at this date some `@ApiResource` attributes are used, for instance `inputClass`. I think it would be better to split `ApiResource` to `ApiRest` and `ApiGraphql` notations in future, to reflect specifics better but for now it sounds stupid for me to not honour not BC-breaking way of managing endpoints.

**Comment by alanpoulain** [comment]
@SCIF Having `@ApiResource` for both GraphQL and REST has advantages and drawbacks.

The main advantage is to be able to share configuration between GraphQL and REST.

The main drawback is to have some keys only applied for REST or GraphQL. It's the case for `collectionOperations`.

I think the best way to solve this would be to have a `rest` key like the `graphql` one with only the specific REST configuration keys, but it would be a big BC break.

In the current state, I think this issue is not valid.
