### ISSUE TITLE
[GraphQL] update mutation doesn't return updated entity type

### ISSUE THREAD

**Issue by nsams** [api-platform/core#2605]
An update mutation returns as payload all fields of the updated entity. But it doesn't return the entity itself, which prevents the client (apollo in my case) to update the cache.

Example of a simple api-platform mutation:

    input updateUserInput {
      id: ID!
      name: String
      clientMutationId: String!
    }

    type updateUserPayload {
      id: ID!
      name: String
      clientMutationId: String!
    }

    mutation UpdateUser($input: updateUserInput!) {
      updateUser(input: $input) {
        id
        name
        clientMutationId
      }
    }

As reference, 
https://facebook.github.io/relay/docs/en/graphql-server-specification.html#mutations does return a nested ship and fraction with their type

and https://facebook.github.io/relay/graphql/mutations.htm also has a nested status (it's type is not visible here though)

**Comment by lukasluecke** [comment]
I think you are right, in that the Payload should instead have a nested field `user`, that resolves to the created entity (since we currently follow the Relay spec in all other regards).

What I am not sure about is how to handle relations / references in the Payload, as the linked example in the Relay specification does (returns both a `Faction` and a `Ship` as nested fields). Maybe just handle the "easy" case first, and think about the rest later?

Also this would be a BC change for everyone using the GraphQL-API, not sure how easy that will be (even though it's still experimental, it's quite a big change - maybe make it configurable?)

**Comment by alanpoulain** [comment]
For the relations / references, we let the user decide by using the normalization context.

It would be a big BC break, yes but:
- we say we follow the Relay spec and this is not the case here;
- GraphQL support is still experimental to allow this kind of change.

I think we should do it, even for 2.4.

**Comment by lukasluecke** [comment]
I'm working on the PR right now.

What should be returned for `delete` mutations? Stick with just the ID for now? I can't find anything about that in the Relay spec (or anywhere else).

**Comment by alanpoulain** [comment]
I think sticking with the ID is alright.

**Comment by dunglas** [comment]
> It would be a big BC break

It indeed is a bug fix to me, and this component is still marked as experimental, so BC breaks are allowed by our policy.
