### ISSUE TITLE
One-To-Many non-doctrine entities 

### ISSUE THREAD

**Issue by CvekCoding** [api-platform/core#2740]
Hello!
I think my question is common enough and was asked before, but I didnt find something similar.
So, if I have 2 not-doctrine entities:
```
/**
* ApiResource
*/
class Parent
{
/**
    /**
     * @ApiProperty(identifier=true)
     *
     * @var int
     */
    public $id;

    /**
     * @ApiSubresource()
     *
     * @var Child[]|null
     */
    public $childs = [];
}

/**
 * @ApiResource
 */
class Child
{  
    /**
     * @ApiProperty(identifier=true)
     *
     * @var int
     */
    public $id;
}
```
Then in GraphQl schema I see that both of these classes were recognized by SchemaBuilder, but `Parent` has no proper one-to-many link to `Child` - `childs` property has type `Iterable` instead of `Child[]`.

What am I missing here?

Thanks.

**Comment by alanpoulain** [comment]
This is a known issue. I will fix it when I have some time.

**Comment by Siregacvek** [comment]
@alanpoulain thanks for an answer. How do you think, this is only a Schema Builder issue or it's something what involves many different classes and subsystems of ApiP?
If it's only related to Schema Builder, I can try to investigate this myself and create PR.

**Comment by Maxell92** [comment]
Hello @Siregacvek,

we had some discussion about this issue in https://github.com/api-platform/core/issues/2687. You ca take a look there, I need to write a Behat test for this

**Comment by Siregacvek** [comment]
@alanpoulain @Maxell92 looks like I solved my issue (not sure that this will work for @Maxell92 case). The issue is here https://github.com/api-platform/core/blob/be932e901402000adf54fa38e0b741f36474be79/src/GraphQl/Type/SchemaBuilder.php#L369-L386

In my case when field is a collection of not-doctrine objects, the `$type->getBuiltinType()` returns `array` type, and code falls to wrong case branch. I did the following:
1. Added the method to determine that we are working with array of objects:
```
    private function isArrayOfObjects(Type $type): bool
    {
        return Type::BUILTIN_TYPE_ARRAY === $type->getBuiltinType() &&
            $type->getCollectionValueType() &&
            Type::BUILTIN_TYPE_OBJECT === $type->getCollectionValueType()->getBuiltinType();
    }
```
2. Improved `isCollection` method:
```
    private function isCollection(Type $type): bool
    {
        return ($type->isCollection() && Type::BUILTIN_TYPE_OBJECT === $type->getBuiltinType()) || $this->isArrayOfObjects($type);
    }
```
3. Slightly changed `case` branch for array (quite tricky, don't totally like my implementation but it works):
```
...
            case Type::BUILTIN_TYPE_ARRAY:
            case Type::BUILTIN_TYPE_ITERABLE:
                $graphqlType = $this->graphqlTypes['Iterable'];
                if (!$this->isArrayOfObjects($type)) {
                    break;
                }
...
```
After these changes the schema works fine for me.

But the next problem was that my `childs` field is empty always. I explored the code and noticed, that there is a `CollectionResolver` class which handles my case:
https://github.com/api-platform/core/blob/be932e901402000adf54fa38e0b741f36474be79/src/GraphQl/Resolver/Factory/CollectionResolverFactory.php#L86-L89
It delegates fetching collection to `src/Bridge/Doctrine/Orm/SubresourceDataProvider.php` which of course can't do this. So I was needed to create my custom implementation of `SubresourceDataProviderInterface` and it finally works for me.

@alanpoulain please, let me know if I solved the issue in a wrong way.

**Comment by alanpoulain** [comment]
Should be solved with https://github.com/api-platform/core/pull/3327.
