### ISSUE TITLE
convertInnerFields() must be of the type string, integer given

### ISSUE THREAD

**Issue by antoinebourlart** [api-platform/core#2774]
Hello,

I configured API Platform with Elasticsarch, when i'm trying to run a request, i obtaining the following response :

`Argument 1 passed to ApiPlatform\\Core\\Bridge\\Elasticsearch\\Serializer\\NameConverter\\InnerFieldsNameConverter::convertInnerFields() must be of the type string, integer given, called in /Users/Documents/Projets/website/vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/NameConverter/InnerFieldsNameConverter.php on line 49`

I used the api platform documentation to implement ES.

Elasticsearch Mapping:
```json
{
  "works" : {
    "mappings" : {
      "site" : {
        "_meta" : {
          "model" : """App\Entity\Work\Site"""
        },
        "dynamic_date_formats" : [ ],
        "properties" : {
          "city" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "draft" : {
            "type" : "boolean"
          },
          "id" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "logs" : {
            "properties" : {
              "completion" : {
                "type" : "long"
              },
              "dateFrom" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              },
              "dateTo" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              },
              "equipment" : {
                "properties" : {
                  "id" : {
                    "type" : "text",
                    "fields" : {
                      "keyword" : {
                        "type" : "keyword",
                        "ignore_above" : 256
                      }
                    }
                  }
                }
              },
              "id" : {
                "type" : "long"
              },
              "pilot" : {
                "properties" : {
                  "id" : {
                    "type" : "long"
                  }
                }
              },
              "segment" : {
                "properties" : {
                  "id" : {
                    "type" : "long"
                  }
                }
              },
              "speed" : {
                "type" : "long"
              },
              "status" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              }
            }
          },
          "name" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            },
            "fielddata" : true
          },
          "type" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
    }
  }
}
```

Thank you

**Comment by Sherokhi** [comment]
Same problem.

**Comment by kronus** [comment]
Sorry if I misunderstood, but did you find a solution to the error? Or do I have to use the code above?

**Comment by mjliang** [comment]
Same problem with my `geo_point` type attribute

**Comment by m-mijailovic** [comment]
Same problem here, did anyone manage to find something of help?

**Comment by MakG10** [comment]
In my case the problem was with denormalization of date field from Elasticsearch. 

After some debugging I've noticed that Symfony Serializer tries to denormalize this field using `ApiPlatform\Core\Bridge\Elasticsearch\Serializer\ItemNormalizer` which fails with the error above.

The solution is to make sure that proper normalizers (in my case DateTimeNormalizer) have higher priority than api platform's ItemNormalizer (which is -810). For example:

```
# config/services.yaml
Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        tags:
            - { name: serializer.normalizer, priority: -500 }
```

Or you could also set the priority for ItemSerializer to much lower value, because it has pretty "liberal" `supportsDenormalization` condition.

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
