### ISSUE TITLE
Denormalize subresource don't load data if already in a subresource or DTO 

### ISSUE THREAD

**Issue by betd-sthibault** [api-platform/core#2800]
i try to load collection of subresource in a DTO and the @id is ignored in my collection item .

By digging in the denormalisation i found that in the src/Serializer/AbstractItemNormalizer.php
the $context[self::OBJECT_TO_POPULATE] is not cleaned before deserializing the subresource 

maybe denormalization of subresources collection  into a subresource  wil fail to.

```php
 protected function denormalizeRelation(string $attributeName, PropertyMetadata $propertyMetadata, string $className, $value, ?string $format, array $context)
    {
    ....
            !$this->resourceClassResolver->isResourceClass($className) ||
            $propertyMetadata->isWritableLink()
        ) {
            $context['resource_class'] = $className;
            $context['api_allow_update'] = true;
           // missing  unset($context[self::OBJECT_TO_POPULATE]) ??  
            try {
                if (!$this->serializer instanceof DenormalizerInterface) {
                    throw new LogicException(sprintf('The injected serializer must be an instance of "%s".', DenormalizerInterface::class));
                }
                return $this->serializer->denormalize($value, $className, $format, $context);
            } catch (InvalidValueException $e) {
                if (!$this->allowPlainIdentifiers || null === $this->itemDataProvider) {
                    throw $e;
                }
            }
        }
       
    }
```

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
