### ISSUE TITLE
How to generate docs for subresource of input DTO?

### ISSUE THREAD

**Issue by gustawdaniel** [api-platform/core#2818]
I want to receive the following json:

```
{
   "flat": "string",
   "object": {
      "key": "string"
   }
}
```

I created `DtoInput` class

```
   public $flat;
   /**
    * @var ObjectModel
    */
   public $object;
   public function setFlat(string $flat) { ... }
   public function setObject(ObjectModel $flat) { ... }
```

and class `ObjectModel` 

```
   public $key;
   public function setKey(string $key) { ... }
```

but on link `/api` i can see model

{
  "flat": "string",
  "object": "string",
}

I want to see

```
{
   "flat": "string",
   "object": {
      "key": "string"
   }
}
```

I was tried to use @Groups from `Symfony\Component\Serializer\Annotation\Groups` and `denormalizationContext` but without success. I think problem can be connected with DTO because of without DTO I configured `denormalizationContext` correctly.

**Comment by gustawdaniel** [comment]
I created repository with exemplary code.

https://github.com/gustawdaniel/api-dto-subresource

Most interesting are README.md and this commit

https://github.com/gustawdaniel/api-dto-subresource/commit/5a8214ac2ae4c4341452b2234be20cd1adcff538

**Comment by gustawdaniel** [comment]
I changed paths in config to `        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Model']` and  added `normalizationContext={"groups"={"read"}}` to Book, and 

`@Groups({"read"})` to any interesting property, then `@ApiResource()` to Attribute and `@ApiProperty(identifier=true)` to key in Attribute. Then model was fixed but i have now not needed endpoints.

When I removed `@ApiResource()` from Attribute or use

```
/**
 * @ApiResource(
 *     itemOperations={},
 *     collectionOperations={}
 * )
 */
```

then I lost model shape that I want to have

**Comment by prodigeris** [comment]
Same here.

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
