### ISSUE TITLE
Exporting OAS 3 for API Gateway generates a Swagger 2.0 file

### ISSUE THREAD

**Issue by farazive** [api-platform/core#2821]
PHP version: 7.2
Symfony Version: 4.2
api-platform/core: 2.4.3

running the command 
```bash
bin/console api:swagger:export  -y -o gateway.yaml --api-gateway --spec-version=3

[OK] Data written to gateway.yaml (specification version 3).      
```

But the gateway.yaml file is a swagger 2.0 file. The first line of the file is 
```text
swagger: '2.0'
```

**Comment by dunglas** [comment]
It has been done like this because API Gateway wasn't supporting OpenAPI v3 until recently. It is now supported according to https://aws.amazon.com/fr/about-aws/whats-new/2018/09/amazon-api-gateway-adds-support-for-openapi-3-api-specification/.

A PR to add support for OpenAPI v3 in the AWS Normalizer is very welcome (/cc @vincentchalamon).

**Comment by soyuka** [comment]
Using https://api-platform.com/docs/master/core/openapi/#overriding-the-openapi-specification (master, or 2.6) and https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html making open api work with AWS should be really easy, not sure we even need to add code ourselves ?
