### ISSUE TITLE
Group filter on item operations not exposed in OpenAPI

### ISSUE THREAD

**Issue by ypereirareis** [api-platform/core#2826]
Hi,

Thanks for your amazing project ! :+1: 

I recently used group filter to expose (or not) data when querying my api endpoints depending on the context. It's working perfectly well !!!

I wanted to filter what data I expose calling **Item Operation** but it's seems that it's not possible to do the same thing.

Is there a solution or workaround to give serialization groups as query params calling an Item operation ?

Thanks !!

**Comment by antograssiot** [comment]
GroupFilter is already supposed to work for item operation
It is even test [here](https://github.com/api-platform/core/blob/master/features/serializer/group_filter.feature#L567-L715)

**Comment by ypereirareis** [comment]
OK. I admit I didn't test it because nothing is generated for swagger ui and doc. Or maybe my yaml configuration is wrong.

I configured group filter the same way as for collection operation but nothing in the swagger doc.

Am I missing something? 

Thx

**Comment by jameslmoser** [comment]
It works for itemOperations, but it doesn't seem to add swagger unfortunately.

**Comment by SylvainNConnect** [comment]
I confirm that :
- groups are managed for item operation like collection operation fortunately
- openapi doc display the group filter for collection operation but not for item operation unfortunately

So it would be a great enhancement to add it in openapi doc and in swaggerUI

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
