### ISSUE TITLE
Computed field or expression search filter?

### ISSUE THREAD

**Issue by danaki** [api-platform/core#2848]
Hello,

I'm trying to implement a custom filter on a computed value. My entity looks approximately like:
```
/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductionPlanRepository")
 * @ORM\Table()
 * @ApiResource(
 *     graphql={
 *         "query"={"normalization_context"={"groups"={"production_plan:query"}}}
 *     }
 * )
 * @ApiFilter(CompletedQuantityProductionPlanFilter::class, properties={"remainingQuantity"})
 */
class ProductionPlan {
    /**
     * @var ?int
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @Groups({"production_plan:query"})
     */
    protected $plannedQuantity;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @Groups({"production_plan:query"})
     */
    protected $producedQuantity;

    /**
     * @var int
     * @Groups({"production_plan:query"})
     */
    protected $remainingQuantity;
```

RemainingQuantity is the computed field which is calculated by a simple formula.
```
RemainingQuantity = PlannedQuantity - ProducedQuantity
```

And I want to filter by this property basically RemainingQuantity > 0.
However, my custom filter like in this example doesn't appear valid because remainingQuantity is not an entity field. How do I achieve my goal?

**Comment by soyuka** [comment]
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/aggregate-fields.html may help you. I'd definitely alter the query and sort by this result in SQL directly.

**Comment by danaki** [comment]
Of course, but I cant figure out how to register this computed field as a filtered, because if a field in "properties" isnt registered with Doctrine inside Entity, filter just dropped.

**Comment by alguintu** [comment]
Hi danaki! I'm currently trying to solve the same problem. Were you able to find a solution? Thank you.

**Comment by danaki** [comment]
> Hi danaki! I'm currently trying to solve the same problem. Were you able to find a solution? Thank you.

I solved it by introducing a "real" field which is updated every time depending fields are getting updated. Doing so you can apply regular filters on this field. However I think API platform should implement this feature to keep things simple and for DRY.

**Comment by jamesisaac** [comment]
If you're talking about a value computed in the PHP entity at runtime: API Platform filters work by adding conditions to the query builder.  They need to happen at that stage so they can fetch the right number of results for the currently selected pagination etc.  Otherwise they'd have to fetch every single record from the database to compute the value at runtime and compare with the filter?  So wouldn't be a scalable design.  I suppose you could achieve this with a [custom DataProvider](https://api-platform.com/docs/core/data-providers/#custom-collection-data-provider) though if it's essential.

If you're talking about something which can be computed in Doctrine by adding to the querybuilder: you can write [custom filter](https://api-platform.com/docs/core/filters/#creating-custom-filters) for this.  Implement `ContextAwareFilter` instead of `AbstractFilter` (the latter is tied to the entity's properties, but the former isn't, so you can do whatever you want in there).

**Comment by danaki** [comment]
No, not computed by doctrine in a querybuilder. A simple getter with an annotation in an Entity class. Serialization from object to json in normalization phase could do the trick.

**Comment by danaki** [comment]
Ok, so if this is impossible, let's close the issue.

**Comment by soyuka** [comment]
Greetings! We appreciate your concern but weren't able to reproduce this issue or it is more of a question. As described in the [API Platform contributing guide](https://github.com/api-platform/core/blob/main/CONTRIBUTING.md), we use GitHub issues for bugs and feature requests only.

For support question ("How To", usage advice, or troubleshooting your own code), you have several options:

- Community Support: ask questions about API Platform on [Stack OverFlow](https://stackoverflow.com/questions/tagged/api-platform.com), or chat with the community on the [api-platform channel on Symfony's Slack](https://symfony.com/slack).
- Commercial support: [Les-Tilleuls.coop](https://les-tilleuls.coop/en) provides professional services for API Platform, [Mercure](https://mercure.rocks/), [Vulcain](https://mercure.rocks/) and [Symfony](https://symfony.com/) including training, development and API design. [Contact them](https://les-tilleuls.coop/en/contact) for more information.

Feel free reach one of the support channels above. In the meantime we're closing this issue.
