### ISSUE TITLE
Computed property went missing from 2.4.3 to 2.4.4

### ISSUE THREAD

**Issue by bobdenotter** [api-platform/core#2858]
We have a computed property on an entity, like: 

```php
    /**
     * @Groups("get_field")
     */
    public static function getType(): string
    {
        return 'generic';
    }
```

Up until version 2.4.3 this was included in the output, like this: 

```json
[
  {
    "name": "title",
    "value": [
      "Adipisci ut libero dolores sit consequatur."
    ],
    "type": "text"
  },
  {
    "name": "contentlink",
    "value": [
      "Quae sint sit consequatur iste inventore qui deleniti."
    ],
    "type": "text"
  },
  {
    "name": "slug",
    "value": [
      "adipisci-ut-libero-dolores-sit-consequatur"
    ],
    "type": "slug"
  }
]
```

After the update to 2.4.4, this property is gone: 

```json
[
  {
    "name": "title",
    "value": [
      "Adipisci ut libero dolores sit consequatur."
    ]
  },
  {
    "name": "contentlink",
    "value": [
      "Quae sint sit consequatur iste inventore qui deleniti."
    ]
  },
  {
    "name": "slug",
    "value": [
      "adipisci-ut-libero-dolores-sit-consequatur"
    ]
  }
]
```

Is this a small bug / regression, or something that we've missed?

**Comment by teohhanhui** [comment]
I'll take a look.

**Comment by teohhanhui** [comment]
Does it work if you add `type` as an attribute in the Serializer mapping?

**Comment by teohhanhui** [comment]
Hmm... But https://github.com/api-platform/core/pull/914

**Comment by teohhanhui** [comment]
This has been there for a long time: https://github.com/api-platform/core/blob/v2.4.3/src/Metadata/Property/Factory/AnnotationPropertyNameCollectionFactory.php#L76-L78

Perhaps it was "working" because of a bug?

**Comment by JarJak** [comment]
@teohhanhui but why static methods with proper serialization group are excluded from api output?

**Comment by teohhanhui** [comment]
@JarJak Good point. I think it shouldn't be. I'll look into this.

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
