### ISSUE TITLE
allow_plain_identifiers is not working for JSONAPI

### ISSUE THREAD

**Issue by maximgubar** [api-platform/core#2962]
Steps to reproduce:

- set `allow_plain_identifiers ` to true in `api_platform.yaml`
- request any resource from API

Expected result:

plain ID is used for `id` property

Actual Result:

IRI is used for `id` property

**Comment by bendavies** [comment]
json LD too.

**Comment by do-web** [comment]
When this will be fixed?

**Comment by maximgubar** [comment]
any estimations on this ?

**Comment by soyuka** [comment]
If you keep this disabled you can use your '.id' no?

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
