### ISSUE TITLE
OpenAPI v3 "links components" seem broken

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#3048]
#2414 seems to be broken, as least with version 2.4.

**Comment by bpolaszek** [comment]
Checked with @dunglas, link components are actually supported on POST operations only (resource creation).

Todo:

- [ ] Add support everywhere it could be needed
- [ ] Return Iri reference (`@id`) when possible.

**Comment by teohhanhui** [comment]
Hmm... #2419 was very weird as it added a link from the `POST` operation to the `GET` operation of the same resource.

While it's not incorrect, it's not typically what you'd have in mind...

**Comment by teohhanhui** [comment]
The implementation of #2419 was problematic as it made too many assumptions.

I'm trying to make `getLinkObject` pass the correct `$options` to the metadata factories, as part of #3425, but this is not possible because of the architecture (`getLinkObject` is only called in the context of the `GET` item operation, whereas we actually need the context of the operation for which the response is being computed).
