### ISSUE TITLE
Creating custom filters without constuctor throw an error

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#3049]
It's not possible to create a filter without a constructor with and a `array $properties` parameters, because of how we wire the class passed as parameter of `@ApiFilter`, we should handle this case, and allow to create custom filters without constructor.

Also when using the default Dependency Injection configuration of Symfony 4, classes passed as parameters of `@ApiFilter` are registered two times, one time by Symfony's autowiring, one time by our compiler pass. If there are no constructors, it's useless and we should prevent this.

**Comment by soyuka** [comment]
Code link: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php

**Comment by LouisPinsard** [comment]
Hello @dunglas @soyuka 

I would love to help on that matter.
I am not sure of what you mean, do you target to be able to write something like that ?
```
**
* @ApiFilter(CustomFilter::class)
*/
class DummyEntityFilterAnnotated
```

What is the use case for such a filter ?
Thanks !

**Comment by soyuka** [comment]
Filters do change the query so it could add whatever :). 

Doing this should be active on every property of the class I guess. The issue here is more when you have a filter without constructor it still adds arguments (https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php#L80) and obviously fails.

**Comment by LouisPinsard** [comment]
@soyuka Ok thanks I'll have a look at it this week
