### ISSUE TITLE
EventSubscriber does not work for graphql

### ISSUE THREAD

**Issue by BernardA** [api-platform/core#3081]
For user registration, I have an `EventSubscriber` to encode password, generate confirmation token and finally to send email confirmation to the user. 

This works fine in `REST` but not at all in `graphql`. 

Searching in this repository I found a couple of issues related to this, including [this one](https://github.com/api-platform/core/pull/2329), but it is not clear to me the current status. 

It seems to have been merged but the issue is present on my installation with 
`"api-platform/api-pack": "^1.2",`.

This is the code in case of need: 

     <?php

     namespace App\EventSubscriber;

    use App\Entity\User;
    use App\Email\Mailer;
    use App\Security\TokenGenerator;
    use Symfony\Component\EventDispatcher\EventSubscriberInterface;
    use Symfony\Component\HttpKernel\KernelEvents;
    use ApiPlatform\Core\EventListener\EventPriorities;
    use Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent;
    use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
    use Symfony\Component\HttpFoundation\Request;

    class UserRegisterSubscriber implements EventSubscriberInterface
    {
    /**
     * @var UserPasswordEncoderInterface
     */
    private $passwordEncoder;
    /**
     * @var TokenGenerator
     */
    private $tokenGenerator;
    /**
     * @var Mailer
     */
    private $mailer;

    public function __construct(
        UserPasswordEncoderInterface $passwordEncoder,
        TokenGenerator $tokenGenerator,
        Mailer $mailer
    )
    {
        $this->passwordEncoder = $passwordEncoder;
        $this->tokenGenerator = $tokenGenerator;
        $this->mailer = $mailer;
    }

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::VIEW => ['userRegistered', EventPriorities::PRE_WRITE],
        ];
    }

    public function userRegistered(GetResponseForControllerResultEvent $event)
    {
        $user = $event->getControllerResult();
        $method = $event->getRequest()->getMethod();
        if (!$user instanceof User ||
            !in_array($method, [Request::METHOD_POST])) {
            return;
        }
        $user->setPassword(
            $this->passwordEncoder->encodePassword($user, $user->getPassword())
        );

        // Create confirmation token
        $user->setConfirmationToken(
            $this->tokenGenerator->getRandomSecureToken()
        );

        // Send e-mail here...
        $this->mailer->sendConfirmationEmail($user);
    }
    }

**Comment by alanpoulain** [comment]
Events are not working with GraphQL.
If you're using 2.5, you can decorate the stages instead to have the same features: https://api-platform.com/docs/master/core/graphql/#workflow-of-the-resolvers
I'm working on a bundle to add events but no release date yet.

**Comment by dunglas** [comment]
See https://github.com/api-platform/docs/issues/866

**Comment by BernardA** [comment]
Thanks @dunglas. The document you linked to is a bit beyond my comfort level. I will see if I can grasp it.

**Comment by SlimenTN** [comment]
Any update on this? still can't use event subscriber with GraphQL

**Comment by alanpoulain** [comment]
If you really want to use events (which I do not recommend), you can use this bundle: https://github.com/alanpoulain/ApiPlatformEventsBundle

**Comment by SlimenTN** [comment]
@alanpoulain why not recommended ?
besides I have tried the decorated stages as you mentioned above but does not fulfill my needs

**Comment by alanpoulain** [comment]
Why doesn't it fulfill your needs?

**Comment by SlimenTN** [comment]
@alanpoulain I will give you an example
I have entity `MediaObject` that contains `filePath` and `contentUrl` attributes
the `filePath` contains the media name (example: image.jpg)
I want when I make a graphql request on this `MediaObject` to get the **full URL** of the media within the `contentUrl` attribute.
the decorated stages works fine when I make a query directly on this object
but let's say I have `Product` entity that has `ManyToOne` relation with the `MediaObject` that contains the image of the product
whe I use decorated stage, and specifically the `api_platform.graphql.resolver.stage.serialize`, and make a query on product there is no why to check nested objects within the product entity and find the `MediaObject` entity and fill the `contentUrl` attribut.
and even more, let's say I have many other entities that has `ManyToOne` relation with the `MediaObject` object how fill the `contentUrl` each time I make a query on objects that has relation with it ?
that's why I wanted to make and event subscriber (which is recommanded by api-platform itself check this https://api-platform.com/docs/core/file-upload/#resolving-the-file-url) to make modification on the `MediaObject` each time its been serialized.

**Comment by alanpoulain** [comment]
Why not using a custom serializer?

**Comment by SlimenTN** [comment]
@alanpoulain and how to do it ?

**Comment by alanpoulain** [comment]
For instance: https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-adding-extra-data
