### ISSUE TITLE
Resource "Doctrine\Common\Collections\Collection" not found in .

### ISSUE THREAD

**Issue by Aerendir** [api-platform/core#3302]
The error is this:

> Resource "Doctrine\Common\Collections\Collection" not found in . (which is being imported from "/app/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.

I'm opening this issue only for reference: this is a common error and there is no documentation on Google about how to solve it.

As this happen wuit frequently to me, I will post the solution here.

No support is required for me. I will edit this post and close the issue once I will have found again the solution.

**Comment by Aerendir** [comment]
This error is caused by a wrong naming of getters and setters.

Take this example:

```php
class MyApiPlatformClass {
    private $myApiProperty;
    
    public function setProperty($property)
    {
        ...
    }
    
    public function getProperty()
    {
        ...
    }
}
```

Then the error above will be thrown.

Internally, ApiPlatform uses `PropertyAccess` Symfony component.

This component reads also the getters and setters.

So, the mismatch between the property name and its getters and setters causes the error.

To fix it, simply change the name of the getters and setters:

```php
class MyApiPlatformClass {
    private $myApiProperty;

    public function setMyApiProperty($property)
    {
        ...
    }

    public function getMyApiProperty()
    {
        ...
    }
}
```

Change `setProperty()` to `setMyApiProperty()` and `getProperty()` to `getMyApiProperty()` and the error will be solved.

**Comment by mkilmanas** [comment]
@Aerendir - for future reference (Googlers like me coming here), could you please elaborate your example with data types (typehints)? So far I do not see how Doctrine Collection was involved in this story, and since I don't have property-to-getter name mismatches (`private Collection $settings` vs `function getSettings(): Collection`) I don't understand if this is relevant to my case in any way. Thanks

**Comment by Aerendir** [comment]
@mkilmanas , it is not directly related to the `Collection` itself, so may be your error has different root causes...

**Comment by mkilmanas** [comment]
Yes, it seems that I had a case described in the docs: https://api-platform.com/docs/core/serialization/#collection-relation
Thanks, anyway

**Comment by SherinBloemendaal** [comment]
> Yes, it seems that I had a case described in the docs: https://api-platform.com/docs/core/serialization/#collection-relation Thanks, anyway

Its weird, this happens to me when using specific subresources, i recently added 2 new subresources of an entity and this error appeared. Its weird because the entity already has multiple toMany relations that never had this error.

What is a proper solution? I mean it feels a bit hacky to use `toValues()` to be honest.
