### ISSUE TITLE
Autowiring error when adding arguments to the __constructor

### ISSUE THREAD

**Issue by winzza** [api-platform/core#3384]
**API Platform version(s) affected**: 2.5.4

**Description**  
I description problem on stackoverflow (https://stackoverflow.com/questions/60155121/how-inject-parameter-in-contstruct). But it seems there can't help me.

How inject service in `__constructor` ApiResource ???

**Comment by desmax** [comment]
@winzza you can't do that. you should pass User entity instead.

**Comment by winzza** [comment]
@desmax Thanks for the quick response.
Very sorry. I wanted to automatically add the current authorized user. To check the uniqueness of the record. What should I do?

**Comment by desmax** [comment]
@winzza you could create event listener which would call setUser method and put current user into entity. https://api-platform.com/docs/core/events/ you could use POST_DESERIALIZE. make sure you set user only when creating an entity.

**Comment by winzza** [comment]
@desmax Thanks so much for the advice.

**Comment by desmax** [comment]
@winzza even better approach would be to use DTO https://api-platform.com/docs/core/dto/
but it's a bit harder to do. (can't help much here, since I myself haven't used this approach yet).
Basic idea is that you have simple object with values that comes from user and you convert it to an entity. this way you have much more control.
