### ISSUE TITLE
[Bug] [Easy-Pick] Search on boolean values

### ISSUE THREAD

**Issue by csarrazi** [api-platform/core#352]
It seems that the following line:

https://github.com/dunglas/DunglasApiBundle/blob/1.0/Doctrine/Orm/Filter/SearchFilter.php#L92

makes boolean filters not work. Indeed, both `false` or `0` should be valid input, in the case of a filter on boolean values.

The `empty()` keyword should be replaced by a check to detect whether the value is

* `null`
* an empty array
* an empty string

All other values should be valid.

**Comment by dunglas** [comment]
Until there we used only `0` and `1` (and not `true` and `false`) but why not :-)

**Comment by csarrazi** [comment]
0 does not work either. The collection won't be filtered based on the value if it is equal to `0` or `false`. See http://php.net/manual/en/function.empty.php

**Comment by dunglas** [comment]
The main problem is that this filter is used regardless of the type of the property to filter. We cannot cast automatically  `'false'` to `false` nor `'0'` to `0` because it can be a valid use case to filter a string property by such values.

A first possible solution is to use metadata to do the casting only when applicable (the property of the current class is a string or an int).
Another solution is to introduce a new `BooleanSearchFilter` class with that behavior.

What do you think @csarrazi?

**Comment by dunglas** [comment]
I've make some research and I think that the best to do is to introduce a new `BooleanFilter` and `NumericFilter` (in `master`).

**Comment by csarrazi** [comment]
Sorry for the late answer. A boolean and numeric filter would be the best approach, as the handling of these data types is different.

**Comment by teohhanhui** [comment]
Is this fixed by 61faae2 (#342)?

**Comment by dunglas** [comment]
No, it still need a dedicated filter.

**Comment by Simperfit** [comment]
@dunglas I will try to send a PR for this one, do we have to do 2 PR ? One for the `BooleanFilter` and one for the `NumericFilter`  ? or one for both ?

**Comment by dunglas** [comment]
Ont for both is ok
