### ISSUE TITLE
How to clear the APC cache with api.mapping.cache.apc?

### ISSUE THREAD

**Issue by felicitus** [api-platform/core#355]
I'm using the `api.mapping.cache.apc` cache. During development, I noticed that my system still had old data cached. However, I couldn't figure out how to clear the APC cache, neither programatically nor via a command. 

`php app/console cache:clear` did not help, the cached data was still there.

**Comment by ogizanagi** [comment]
Actually, you can't clear APC cache of your server from a command line unless using some workarounds. This is due to the fact APC cache from cli and server are distinct, not shared.

Usually, restarting your server would clear the cache. Otherwise, the trick is to make a request from CLI to a non-publicly exposed URL pointing to a controller in which you'll call `apc_clear_cache` (or your service's `ClearableCache::deleteAll()` method)

You can also use an APC cache admin that'll allow you to clear user cache.

You can also have a look to:
- https://ma.ttias.be/clear-apc-cache-php/
- http://stackoverflow.com/questions/911158/how-to-clear-apc-cache-entries

**Comment by felicitus** [comment]
I think the best way to clear the cache in my case would be to call apc_clear_cache() during setup. However, I guess it should be mentioned within the documentation.

**Comment by dunglas** [comment]
Actually you should not use APC in your development environment and you should restart PHP to flush the APC cache at each deployment in production. If you don't do that you will face problems with most PHP projects including Symfony.

But why not adding a mention about that in the documentation.

**Comment by teohhanhui** [comment]
FWIW with Symfony 3.1 (framework) the default cache setup may use APCu if available (yes, it's active even in `dev` environment), but there's nonce-based invalidation so it's taken care of for you. :smile:
