### ISSUE TITLE
Dealing with erroneous docblock ? (request for feedback/comment)

### ISSUE THREAD

**Issue by drupol** [api-platform/core#3565]
**Description**  
Hello,

I just took over a new project from a client and it's based on API Platform.
When running `bin/console cache:clear -vvv`, I get this issue: https://del.dog/unupowyghe.txt

It took me a while to figure out where was the issue. I added a couple of `var_dump()` to spot the erroneous docblock.

The issue was in the following entity (_I stripped down the code to the relevant part_):

```php
<?php

namespace App\Entity;

class Foo
{
    /**
     * @var
     * @ORM\Id
     * @ORM\Column(name="FOO_ID", type="integer")
     */
    private $fooId;
}
```

Basically there is an error which is triggered because the tag `@var` without a value is an [InvalidTag](https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/Tags/InvalidTag.php). As `InvalidTag` doesn't have the method `getDescription()`, it fails.

I was wondering what would be the best way to fix this for the people who, like me, are spending hours finding where such an issue could be in a huge project.

I investigated [phpDocumentor/ReflectionDocBlock](https://github.com/phpDocumentor/ReflectionDocBlock/) and changed [InvalidTag](https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/Tags/InvalidTag.php) so it extends [BaseTag](https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/Tags/BaseTag.php), and thus, have a [getDescription()](https://github.com/phpDocumentor/ReflectionDocBlock/blob/cd72d394ca794d3466a3b2fc09d5a6c1dc86b47e/src/DocBlock/Tags/BaseTag.php#L40) method.

Of course, when I do that, I can clear the cache of the project and I get no more issue.

Unfortunately, I have the feeling that this is not the proper way to fix the issue.

I think the best way to fix this would be to return a proper error to the user, a bit like this:

`"InvalidTagException: The property tag @var cannot be empty, fix it or remove it in file [FILE] at property [PROPERTY]."`

So, I don't mind taking care of the issue, but before, I'd like to have some feedback and some directions if possible.

Thanks!

**Comment by GregoireHebert** [comment]
Hi @drupol 
To me this is indeed something that could/should be done directly in phpdocumentor library, so everyone can benefit from this :)

**Comment by drupol** [comment]
Implemented in https://github.com/phpDocumentor/ReflectionDocBlock/pull/221

**Comment by jaapio** [comment]
I think phpDocumentor/ReflectionDocBlock is not the correct place to handle this. As I explained to @drupol on slack.

The `Docblock` class will return a list of [`Tag`](https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/Tag.php) objects. The `getDescription` method is not part of the interface `Tag`. Tools like phpstan will actually error on this, since you are calling a none existing method. 

The `InvalidTag` was introduced to be able to report issues about invalid docblock tags, without making phpDocumentor or other tools crash. This issue is related to https://github.com/symfony/symfony/issues/36049.

I think this should be fixed in symfony. Not in phpDocumentor or api-platform. :-)
