### ISSUE TITLE
ManyToMany relationship breaks system with Uncaught LogicException

### ISSUE THREAD

**Issue by phtmgt** [api-platform/core#3596]
**API Platform version(s) affected**: 2.5.9

**Description**
When a ManyToMany relationship is exposed on both sides, I get a critical error.

**How to reproduce**  
Create a ManyToMany relationship and expose both sides. For example:

Class Business:
```
/**
     *
     * @ORM\ManyToMany(targetEntity="User", inversedBy="businesses")
     * @ORM\JoinTable(name="companies_owners")
     * @Expose
     * @MaxDepth(1)
     * @SkipWhenEmpty
     * @ApiSubresource
     * @Groups({"read"})
     */
    private $owners;
```

Class User:
```
/**
     *
     * @ORM\ManyToMany(targetEntity="Business", mappedBy="owners")
     * @Expose
     * @MaxDepth(2)
     * @SkipWhenEmpty
     * @ApiSubresource
     * @Groups({"read"})
     */
    public $businesses;
```

Then you get the following error:

` php.CRITICAL: Error: Uncaught LogicException: Route pattern "/platform/api/properties/{id}/owners/{owners}/business/owners/{owners}/employers.{_format}" cannot reference variable name "owners" more than once.
`
**Possible Solution**  
Tried limiting depth, doesn't work.

**Additional Context**  
This has been breaking the app constantly and I have to always find ways to hack my way to the data I need. I posted in a similar issue, but no one's answering.

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
