### ISSUE TITLE
Request interceptors planned?

### ISSUE THREAD

**Issue by tebaly** [api-platform/core#3624]
**Description**  

Is something like request interceptors planned?

Sample scheme (spring-boot-interceptors)
![image](https://user-images.githubusercontent.com/9466814/85881248-fa1fc000-b7e5-11ea-9f1d-f551a25dfe4b.png)

I tried to implement. This is an outline. I use in my project.

**Example**  
https://github.com/freedomsex/api-interceptor-bundle

**Comment by dunglas** [comment]
API Platform provides a lot of extension points to hook your custom logic: https://api-platform.com/docs/core/extending/

As described in the description of the bundle you pointed out, "Interceptors" correspond more or less to the "Events Listeners": https://api-platform.com/docs/core/events/

Since Symfony 4, using annotations (as dine by this bundle) is not really necessary anymore because you can use what is called "auto configuration" instead: https://symfony.com/doc/current/event_dispatcher.html#creating-an-event-subscriber

If you plan to use GraphQL, we strongly encourage you to use the other, generic, extension points available instead of the kernel events, because a single HTTP request can contain several GraphQL requests.
