### ISSUE TITLE
Huge list of urls to be generated - cannot clear cache, out of memory, execution timeout

### ISSUE THREAD

**Issue by plamenh** [api-platform/core#3640]
**API Platform version(s) affected**: 2.4.9

**Description**  
Cannot clear cache, because of too many urls to be generated

**How to reproduce**  
Add a fair amount of entities, try to clear cache. var/cache/dev/UrlGenerator.php does not execute, complains about memory with 1G+ dedicated to it. In dev and prod always times out on first load (30+ seconds).

**Possible Solution**  
Since I don't need anything else, but GraphQL, is there a way to disable the regular API, so we don't end up with a 20K+ urls to be generated?

**Additional Context**  
20K+ lines of UrlGenerator.php
Errors at random url generation related operations

**Comment by soyuka** [comment]
I think I answered that before, currently there's no options to do so. Still I see two options:

1) create a ResourceMetadataFactory that overrides every operations so that [this loop](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/ApiLoader.php#L101) doesn't add routes.
2) override the ApiLoader completely (https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/ApiLoader.php#L101)

**Comment by plamenh** [comment]
@soyuka thanks for the tip. I did override ApiLoader (just commented out lines 124 - 144) and it works for me.
