### ISSUE TITLE
Exception for unauthenticated user with update Symfony security system

### ISSUE THREAD

**Issue by tjveldhuizen** [api-platform/core#3680]
**API Platform version(s) affected**: 2.5.6

**Description**  
When using the updated Symfony security system (https://symfony.com/blog/new-in-symfony-5-1-updated-security-system), in case of an unauthenticated user the `getToken()` method of the TokenStorageInterface [returns null](https://symfony.com/doc/current/security/experimental_authenticators.html#adding-support-for-unsecured-access-i-e-anonymous-users). Due to this implementation, the ResourceAccessChecker of Api Platform throws an Exception when a resource containing a 'security'-setting of `"GET"={"security"="is_granted('ROLE_USER')"}`, suggesting the API is not behind a firewall.

**How to reproduce**  
 - Create a new Symfony 5.1.3 project
 - Add Api Platform 2.5.6
 - [Create a custom authenticator](https://symfony.com/doc/current/security/experimental_authenticators.html#creating-a-custom-authenticator)
 - Create a resource containing a security setting like `"GET"={"security"="is_granted('ROLE_USER')"}`
 - Access the resource in an unauthenticated session

**Possible Solution**  
It might be enough to remove this lines, but maybe that's not very helpful for users failing to enable the firewall? Unfortunately, I don't have enough knowledge of the ecosystem to know if a better solution exists https://github.com/api-platform/core/blob/38d69e6fdeaa6d6d32d43b7467454acb17d11315/src/Security/ResourceAccessChecker.php#L51-L53

**Comment by weaverryan** [comment]
This changes slightly in https://github.com/symfony/symfony/pull/37620

But yea, it IS true that anonymous users don't have a token in the tokenStorage anymore.

In normal cases, you won't notice this after the above PR because a `NullToken` is added by the `AuthorizationChecker`. However, if you're "sort of" executing some security logic on your own (like it seems in this case), then I guess you'll need to initialize to a `NullToken` manually.
