### ISSUE TITLE
After updading api-pack from 1.1.0 to 1.3.0 I lost IRI's inside ManyToOne relations

### ISSUE THREAD

**Issue by zim32** [api-platform/core#3717]
**API Platform version(s) affected**: 1.3.0

**Description**  
After updading api-pack from 1.1.0 to 1.3.0 I lost IRI's inside ManyToOne relations

Was in 1.1.0
```
"projectType":{
      "@id":"\/cms-api\/project_types\/1",
      "@type":"ProjectType",
      "id":"1",
      "title":"WordPress"
   },
```
After update to 1.3.0:
```
"projectType":{
      "id":"1",
      "title":"WordPress"
   },
```

What could be wrong?

**Comment by zim32** [comment]
If I set 
```
<service id="api_platform.jsonld.normalizer.item" class....
    <tag name="serializer.normalizer" priority="8" /> instead of 
    <tag name="serializer.normalizer" priority="-890" /> as in version 1.3.0 
```
everuthing work like expected. This is a bug or feature?

**Comment by zim32** [comment]
How can you replace the priority of your normalizer without incrementing major version. How many developers in this world does not respects semver? I am very disappointed

**Comment by dunglas** [comment]
> How can you replace the priority of your normalizer without incrementing major version. How many developers in this world does not respects semver? I am very disappointed

Bugs happen, and it's very hard to be sure that a bug fix or actually any other change will not have negative impact on any of the many existing API Platform projects. What would help instead of this kind of comment is to find which patch introduced this change, and why (using `git bisect` for instance) so we can try to fix this regression.
