### ISSUE TITLE
Identifiers with custom serialized_name show incorrect name in SwaggerUI Links section

### ISSUE THREAD

**Issue by maxtorete** [api-platform/core#3788]
**API Platform version(s) affected**: 2.5.7

**Description**  
When you set a serialized_name to an identifier property, SwaggerUI shown the serialized_name in the schema, but in the SwaggerUI operations Links section the original property name is shown ignoring the custom [serialized_name](https://symfony.com/blog/new-in-symfony-4-2-simpler-custom-serialized-names).

**How to reproduce**  
Set a serialized_name to a identifier property in a Resource, then go to SwaggerUI and check Links section.

**Possible Solution**  
See pull request.

**Comment by velreine** [comment]
I'm curious because I have a problem with the @SerializedName annotation as well where it is ignored during denormalization I use this on a field called $plainPassword with @SerializedName("password") to make it so user passwords are encoded at creation (POST) etc.

This has stopped working for me also in 2.5.7 and with Symfony 5.1, and I know this has previously worked. I have an extra configuration on the SerializerContextBuilder so that "extra" attributes are not allowed, this way the API will return a bad request (400) when it detects attributes that are not allowed (as they would otherwise just be silently ignored).

I want to keep myself updated on this topic, as this also affects me being able to have Computed/Calculated fields/values, and I think your issue might be related to this.

**Comment by maxtorete** [comment]
> I'm curious because I have a problem with the @SerializedName annotation as well where it is ignored during denormalization I use this on a field called $plainPassword with @SerializedName("password") to make it so user passwords are encoded at creation (POST) etc.
> 
> This has stopped working for me also in 2.5.7 and with Symfony 5.1, and I know this has previously worked. I have an extra configuration on the SerializerContextBuilder so that "extra" attributes are not allowed, this way the API will return a bad request (400) when it detects attributes that are not allowed (as they would otherwise just be silently ignored).
> 
> I want to keep myself updated on this topic, as this also affects me being able to have Computed/Calculated fields/values, and I think your issue might be related to this.

It could be related, but my fix is only for the Documentation Normalizer. In my app normalization/denormalization works fine with custom serialized name, but in Swagger UI the original property name is displayed instead. 

I'm not using any SerializerContextBuilder customization, so the problem could be there.

**Comment by soyuka** [comment]
should be fixed in 2.6 alpha
