### ISSUE TITLE
Swagger UI always displays empty default and example keys

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#3882]
**API Platform version(s) affected**: 2.6.0 alpha, maybe 2.78

**Description**  

<img width="477" alt="image" src="https://user-images.githubusercontent.com/57224/101237573-439c0180-36da-11eb-8660-0aff9b192979.png">

**How to reproduce**  

Use this entity: https://github.com/api-platform/api-platform/blob/master/api/src/Entity/Greeting.php

**Possible Solution**  

Check for empty values here: https://github.com/api-platform/core/blob/master/src/JsonSchema/SchemaFactory.php#L195-L201

**Comment by guilliamxavier** [comment]
I'm wondering: for a `public string $name = '';`, wasn't it just logical to generate `"default": ""`?

I'm asking because now (after the change of `null !==` to `!empty()`) I have kind of the opposite issue:

I have a `public bool $consent = false;` and it doesn't generate `"default": false`, and in Swagger UI for the POST endpoint the example body has `"consent": true` :confused:

But in my case I can still add an explicit `#[ApiProperty(openapiContext: ['default' => false])]`, while I indeed found no way of removing a generated default... 😞

**Comment by alanpoulain** [comment]
We should probably be stricter then: only `null` and `''` should be invalid and we shouldn't use `empty`.

**Comment by guilliamxavier** [comment]
> We should probably be stricter then: only `null` and `''` should be invalid and we shouldn't use `empty`.

Maybe, but I wouldn't want to mess with potential uses... I can also imagine e.g. a

```php
    #[Assert\Positive()]
    public int $quantity = 0;
```

where the `= 0` is only used to avoid an Error "Typed property [...] must not be accessed before initialization" but is actually not a valid value and is not wanted to be documented as a default (that apparently there would be no way to remove)...

(Sorry I'm the one who complained and now I'm refraining, just thinking out loud)
