### ISSUE TITLE
Schema test wrong since v2.5.8: tested working on 2.5.7

### ISSUE THREAD

**Issue by FrankHouwelingCastor** [api-platform/core#3896]
v2.5.8

**Description**  
The json schema in the test is different from the json schema in documentation and from the json schema of the API response.

**How to reproduce**  
![image](https://user-images.githubusercontent.com/69353572/101617741-4f0c6700-3a11-11eb-9181-7a7885c3d647.png)

```
static::createClient()->request('GET', '/studies');
        self::assertResponseIsSuccessful();
        self::assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

        self::assertMatchesResourceCollectionJsonSchema(Study::class);
```

Will return:
hydra:member[0].roles[0].user: Object value found, but a string is required

If I var_dump the schema that is being generated by the ApiTestAssertionsTrait::assertMatchesResourceCollectionJsonSchema function it indeed expects a string. This is different from the output of the API docs, and also from what the API returns.

This functionality is broken because of the api-platform/core update (v2.5.7 => v2.5.8). Tested to be working before the update of these packages, with the same code.

**Comment by madrzejewski** [comment]
I have the same issue here, all my tests passed on 2.5.7 and just after updating to 2.5.9 I have errors on the `assertMatchesResourceItemJsonSchema` test but the response seems fine to me.

```
Failed asserting that Array &0 (
    '@context' => '/api/contexts/Template'
    '@id' => '/api/templates/112237'
    '@type' => 'Template'
    'id' => 112237
    [....]
    'additionalsParams' => Array &3 (
        'purgeSecret' => '2c4eb408-f224-44b7-b2aa-69d2877d2bc9'
    )
) matches the provided JSON Schema.
additionalsParams: Object value found, but an array is required
```

**Comment by alanpoulain** [comment]
See https://github.com/api-platform/core/issues/3918. The assertion was not working at all before.

**Comment by madrzejewski** [comment]
@alanpoulain Thanks for your answer. Any ideas how I can correct such error ? I'm assuming I'm doing something wrong but I don't see anything weird. I'm new to Api Platform, I'm following the doc for the testing, I'm not familiar with any of this at this moment. 

I think the problem is in the entity, on the comment around the property ? 

```
    /**
     * @ORM\Column(type="array", nullable=true)
     * @ConstraintCustomJson(type="customHeaders")
     * @Groups({"template:read", "template:write", "template:item:patch"})
     */
```

**Comment by alanpoulain** [comment]
Not sure why. It seems your array in the response is not serialized correctly (as an object whereas it should be an array).

**Comment by madrzejewski** [comment]
Yes, it seems so. When the array is empty, it's working, when I have something, it's seems to transform into an object. I'm digging, if I dd() inside the validator, I'm seeing this for instance : 

```
MatchesJsonSchema.php on line 82:
{#2702
  +"@context": "/api/contexts/Template"
  +"@id": "/api/templates/117278"
  +"@type": "Template"
  +"id": 117278
  [... truncated ...]
  +"customHeaders": {#2597
    +"X-O2-Template": "wordpress"
    +"X-O2-Purge-Key": "798c73a2-200e-40d3-9db6-51d3712833cb"
  }
  +"templateName": "default"
  +"additionalsParams": []  
}
```

**Comment by yakobe** [comment]
I also have this problem. This seems to be the commit that breaks it: https://github.com/api-platform/core/commit/7595ac7c17eecd5be320026583c040c44c9ed851

It seems that adding `[AbstractNormalizer::ALLOW_EXTRA_ATTRIBUTES => false]` as a `$serializerContext` parameter means that it is not properly resolved later in the process. It used to be `null` and then it would be resolved here: https://github.com/api-platform/core/blob/75deb1a6b535fe5cdcf2e9d32174e4c182f4af7a/src/JsonSchema/SchemaFactory.php#L291

Since it is no longer `null` it is returned directly and the serializer groups are not added 😕.

**Comment by yakobe** [comment]
@soyuka and @alanpoulain what bug did https://github.com/api-platform/core/pull/3830 fix? There does not seem to much info there?

Perhaps the `[AbstractNormalizer::ALLOW_EXTRA_ATTRIBUTES => false]` needs to be merged into the serializer context instead?

**Comment by alanpoulain** [comment]
This property ensures that if there are additional properties, the assertion fails.
However I think there is indeed an issue. I think merging the contexts is a bit risky, so maybe the better solution would be to add the other properties ((de)normalization context) in the context.

**Comment by yakobe** [comment]
Any chance we can revert the change that prevents additional properties until a solution is decided? The BC break seems to be worse than the additional feature of preventing extra values 😸.

**Comment by alanpoulain** [comment]
I don't think it would be a good idea to revert it. Without this change, the assertion doesn't really make sense.

**Comment by yakobe** [comment]
Without the change we tests pass as before and we can see that the response returned from the api matches the one defined by the json schema. Ok... we dont see extra properties which would be nice. Meh.

With the change we see these extra properties are added. Cool.
However, no tests will ever pass because it cannot work out what groups to use while serializing. Seems definitely the worse of 2 evils to me.

**Comment by alanpoulain** [comment]
Why not doing a PR to fix it instead of reverting?

**Comment by yakobe** [comment]
I would love to, but I haven't a huge amount of time to research a thorough fix at the moment. My idea of merging the values was not wanted and I'm not sure how your suggestion would be implemented. 

I totally understand the "you found the bug, you fix it" sentiments of open source. But it can be really difficult to get a solution the meets the maintainer's desires and often results in lots of wasted time on implementations that get turned a down. 

The quickest pr from my side would be a revert. Unless you could provide some more information about how you would like it fixed? Then I will have a crack at it when I have time.

**Comment by alanpoulain** [comment]
My proposal is to copy the `getSerializerContext` method from `SchemaFactory` to `ApiTestAssertionsTrait` and merge it with the `[AbstractNormalizer::ALLOW_EXTRA_ATTRIBUTES => false]`.
