### ISSUE TITLE
JSON-LD version of the API documentation does not provide information about the API version

### ISSUE THREAD

**Issue by Kolyunya** [api-platform/core#3929]
**API Platform version(s) affected**: 2.5.9

**Description**  
JSON-LD version of the API documentation does not provide information about the API version.

```
# http://localhost/docs.json
"info": {
    "title": "My API name.\n",
    "description": "My API description.\n",
    "version": "1.0.0"
}
```

```
# http://localhost/docs.jsonld
"hydra:title": "My API name.\n",
"hydra:description": "My API description.\n",
```

**How to reproduce**  
Go to `http://localhost/docs.jsonld` and look for the API version. You're not going to find it there.

**Possible Solution**  
Add information about the API version to the JSON-LD documentation.

**Additional Context**  
I think this is an important feature for the client of the API. For example the mobile application may check the API version on startup and ask user to update itself if the API version is no longer supported.

**Comment by dunglas** [comment]
Hydra hasn't such field. AFAIK (but I may be wrong, I haven't double-checked), no other REST vocabulary provide such property either.

Actually it makes sense because the REST architectural style discourages versioning. REST applications should never introduce hard breaking changes and should follow an evolution strategy instead (the same strategy applies for GraphQL by the way). See https://api-platform.com/docs/core/deprecations/

If you really want to add a custom version field, just use decorate the `ApiNormalizer` class. https://api-platform.com/docs/core/deprecations/
