### ISSUE TITLE
DataProviders called despite not passing security checks

### ISSUE THREAD

**Issue by lazka** [api-platform/core#4098]
This is similar to #4075

I've annotated my entity as follows:

```
 *     itemOperations={
 *         "get" = {
 *             "security" = "is_granted('IS_AUTHENTICATED_FULLY')"
 *         },
 *    }
```

Despite this the associated DataProvider gets called when I make an anonymous request to the API.

Am I missing something?

**Comment by rugolinifr** [comment]
There is no issue, the `ReadListener` is always triggered before the `ValidationListener`. 
Check the [lifecyle](https://api-platform.com/docs/core/events/#custom-event-listeners).

Otherwise, how do you expect to fill the [`object` keyword](https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters) with the current entity ?

```php
/**
 * @ApiResource(
 *     itemOperations = {
 *         "security" = "is_granted('read', object)"
 *     }
 * )
```

**Comment by alanpoulain** [comment]
Thanks for the answer @rugolinifr.
