### ISSUE TITLE
Api-PLatform & Mercure : custom topics

### ISSUE THREAD

**Issue by alexglvr** [api-platform/core#4164]
Hello,

My Users are divided in several user groups.
Most of my entities have a user group fiield refering to the user group they belong too.

when an entry is modified / suppressed I want the SSE message to be sent only to the users belonging to the entry usergroup.
I thought using custom topics for this purpose,

http://server/api/books/1/usergroup1
http://server/api/books/5/usergroup2

 but when specifying the topics option in Api-platform, it overides the original IRI based topic (and it seems to be impossible to get it back...)

In PublishMercureUpdatesListener.php, , publishUpdate function :
`$iri = $options['topics'] ?? $this->iriConverter->getIriFromItem($object, UrlGeneratorInterface::ABS_URL);`

It could also be pratical to specify several topics, including the original IRI based one :

```
/**
 * @ApiResource(
 *   mercure="object.getMercureOptions()",
 * )
  */
function getMercureOptions() {
return [ 
    'private' => false,
    "topics" => [
        originalIriBasedOne, 
        originalIriBasedOne/object.usergroup,
        fullCustomOne,
    ]
]}
```
Thank you,
 Alex

**Comment by hosseinsalemi** [comment]
Same problem.

**Comment by djpremier** [comment]
Hello @alexglvr, I am developing an alternative for this purpose, but at the moment I stopped because I am having to carry out other activities, and we were unable to arrive at a solution that hears agreement.

If you can help, these are the two pull requests I’ve created so far, to try to solve this challenge.

https://github.com/api-platform/core/pull/4150 -> This works, but @dunglas would like to do it differently if possible

https://github.com/api-platform/core/pull/4153 -> This is an attempt to do as suggested, but without success due to the possibility of using URL in topics
