### ISSUE TITLE
GraphQL Resolving fails on nested array property if the serialization group is not set correctly

### ISSUE THREAD

**Issue by nik-lampe** [api-platform/core#4240]
**API Platform version(s) affected**: 2.6.4

**Description**  

Quering on an array property of an nested entity fails with "Resource class cannot be determined" when the serialization group is not set to the one of the normalization context of the outer entity.

**How to reproduce**  
I have created an example repo to reproduce the issue:
https://github.com/nik-lampe/api-platform-graphql-issue

1. clone and install the code from the repo
2. create a book and a review for it
3. run the following query

`{
  reviews {
    edges {
      node {
        id
        body
        book {
          id
          description
          arr
          breakingArr
        }
      }
    }
  }
}
`

**Possible Solution**  

I think it's because the array does not get serialized and thus returns null or something. If you try to query the author field of the book, which also does not have the review_read serialization group you get this error:

Cannot return null for non-nullable field \"Book.author\".",

I guess that's a little misleading, but okay. But the error for the array made me think that there was something wrong with my code, not with the serialization groups, as the schema is generated with the field but resolving it then returns null.

**Comment by DavidBennettUK** [comment]
@alanpoulain I also just ran into this, but with using `ApiProperty` security. It's essentially the same issue, when an array (iterable) field isn't denormalized (either due to not being in the serializer group, or in the allowed properties).
We'd solved a similar issue with collections in [CollectionResolverFactory](https://github.com/api-platform/core/pull/4143/files#diff-928fadd70d45b05d4519eb7667d9a48ba7397b7d9009e91ad59591a7921369e4R63) by returning early if the field isn't in the source array. However, it doesn't look like we can take the same approach with 
 [ItemResolverFactory](https://github.com/api-platform/core/blob/main/src/GraphQl/Resolver/Factory/ItemResolverFactory.php#L62) - so I'm not sure what the best thing to do would be.

**Comment by wcoppens** [comment]
I was wondering is there is any update on this issue yet? this is quite a deal breaker for us. This issue makes it nearly impossible to use a unique normalization group per resource as you would with REST.
The two workarrounds we've found so far is using a single normalization group for all resources such as `read`. But that just doesn't feel right as there are certainly cases in which we definitely want to hide certain props from an entity depending on the dynamic normalization groups.
The other trick is to define the parent entity normalization group also on the child, but then things will get quickly messy as a lot of groups would need to be defined.
