### ISSUE TITLE
Unneeded joins added by ORM DataProvider, Performance issue.

### ISSUE THREAD

**Issue by oliver-schulz** [api-platform/core#4261]
**API Platform version(s) affected**: 2.5.x

**Description**  
I am using a Custom Filter and a QueryExtension with inner joins. In my case i have to make at least 4 joins before i can set my where clause to ensure i will return the right subset of products. All joins which are not in the SELECT part are not needed to get a proper result. The inner query is fine, but the duplicated joins at the outer query are not needed. In this example this query returns half a million rows in a very small dataset on my local machine. I fixed it for now with adding `$queryBuilder->distinct(true)` in order to avoid the large dataset.

This query was build by the CollectionDataProvider after all filters, eager loading and the other extensions were applied.

```
SELECT s0_.code                     AS code_0,
       s0_.created_at               AS created_at_1,
       s0_.updated_at               AS updated_at_2,
       s0_.enabled                  AS enabled_3,
       s0_.id                       AS id_4,
       s0_.variant_selection_method AS variant_selection_method_5,
       s0_.average_rating           AS average_rating_6,
       s0_.logisticService          AS logisticservice_7,
       s1_.name                     AS name_8,
       s1_.slug                     AS slug_9,
       s1_.description              AS description_10,
       s1_.meta_keywords            AS meta_keywords_11,
       s1_.meta_description         AS meta_description_12,
       s1_.id                       AS id_13,
       s1_.short_description        AS short_description_14,
       s1_.locale                   AS locale_17,
       s0_.main_taxon_id            AS main_taxon_id_18,
       s0_.manufacturer_id          AS manufacturer_id_19,
       s0_.brand_id                 AS brand_id_20,
       s1_.translatable_id          AS translatable_id_22
FROM sylius_product s0_
         INNER JOIN sylius_product_channels s3_ ON s0_.id = s3_.product_id
         INNER JOIN sylius_channel s2_ ON s2_.id = s3_.channel_id
         INNER JOIN custom_table_1 c4_ ON s2_.id = c4_.channel_id
         INNER JOIN custom_table_2 f5_ ON c4_.id = f5_.custom_id
         INNER JOIN custom_table_3 c6_ ON s0_.id = c6_.product_id
         INNER JOIN custom_table_4 c7_ ON c6_.custom_id = c7_.id
         INNER JOIN sylius_product_taxon s8_ ON s0_.id = s8_.product_id
         INNER JOIN sylius_taxon s9_ ON s8_.taxon_id = s9_.id
         INNER JOIN sylius_product_translation s1_ ON s0_.id = s1_.translatable_id AND (s1_.locale = ?)
         INNER JOIN sylius_plus_inventory_source s10_ ON c7_.inventorySource_id = s10_.id
WHERE s0_.id IN (SELECT s11_.id
                 FROM sylius_product s11_
                          INNER JOIN sylius_product_channels s13_ ON s11_.id = s13_.product_id
                          INNER JOIN sylius_channel s12_ ON s12_.id = s13_.channel_id
                          INNER JOIN custom_table_1 c14_ ON s12_.id = c14_.channel_id
                          INNER JOIN custom_table_2 f15_ ON c14_.id = f15_.custom_id
                          INNER JOIN custom_table_3 c16_ ON s11_.id = c16_.product_id
                          INNER JOIN custom_table_4 c17_ ON c16_.custom_id = c17_.id
                          INNER JOIN sylius_product_taxon s18_ ON s11_.id = s18_.product_id
                          INNER JOIN sylius_taxon s19_ ON s18_.taxon_id = s19_.id
                          INNER JOIN sylius_product_translation s20_
                                     ON s11_.id = s20_.translatable_id AND (s20_.locale = ?)
                          INNER JOIN sylius_plus_inventory_source s21_ ON c17_.inventorySource_id = s21_.id
                 WHERE s12_.id = ?
                   AND f15_.farmer_id = ?
                   AND c17_.status = ?
                   AND s19_.siteSection = ?
                   AND EXISTS(SELECT 1
                              FROM sylius_product_channels s22_
                                       INNER JOIN sylius_channel s23_ ON s22_.channel_id = s23_.id
                              WHERE s22_.product_id = s11_.id
                                AND s23_.id IN (?))
                   AND s21_.uuid IN (?)
                   AND s19_.tree_left >= ?
                   AND s19_.tree_right <= ?
                   AND s19_.tree_root = ?)
ORDER BY s0_.code ASC
LIMIT 30;
```
Only `sylius_product` and the join onto `sylius_product_translation` are needed in the outer query. The other joins are not needed i think.

Do i do something completely wrong here or did i miss a configuration setting?

**How to reproduce**  
1) create custom filter with some Joins
2) add some QueryExtensions with some joins
3) Debug SQL in CollectionDataProvider

**Possible Solution**  
Removing the joins from the outer query or adding a where to the outer query, the temporary workaround is now to use distinct in in one of my QueryExtensions: `$queryBuilder->distinct(true)`

**Additional Context** 
- My api endpoint uses the ORM CollectionProvider

I have seen this issue #3525 and #2993 , but this is only merged to 2.6.x not to 2.5.x, also not 100% sure if this fixes the QueryExtension / FilterExtension problem i have discovered here.

Related issues:

**Comment by sa-schreiber** [comment]
Any updates on this issue? It causes massive performance problems if databases and queries reach more complexity and content.

I debugged a bit deeper into it and found two major problems with the query modification `ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterEagerLoadingExtension` adds:

**1) Joins are kept but where clauses are removed in the outer query.**

Imagine a query like this:
```

SELECT a.foo, a.bar from a
INNER JOIN b on a.b_id  = b.id
WHERE b.prop = 1;
```

The extension modifies it to:

```
SELECT a.foo, a.bar from a
INNER JOIN b on a.b_id  = b.id
WHERE a.id IN (
	SELECT a.foo, a.bar from a
	INNER JOIN b on a.b_id  = b.id
	WHERE b.prop = 1;
);
```

b could be a table with 10000s of rows - by removing the outer WHERE clause (`where b.prop = 1`) the join may result in a very high number of results.
Think of an MM intermediate table with many rows relating to a.

In the original query of this ticket the same problem is described, but with a chain of joined tables, effectively multiplying the problem.

Possible solution: Remove joins from the outer query that are not used in SELECT or ORDER parts. However, the QueryBuilder does not support removing joins (as it messes up the joinAliases map internally).
So it is necessary to create a new QueryBuilder instance an re-add the joins. The current extension implementation does not allow returning a new QueryBuilder, so this would require a rewrite (maybe not using an extension?).

**2) Limits are not applied to the inner query (possible duplicate to #2993).**

Imagine a query like this:

```
SELECT a.foo, a.bar from a
INNER JOIN b on a.b_id  = b.id
LIMIT 30;
```

The extension modifies it to:

```
SELECT a.foo, a.bar from a
INNER JOIN b on a.b_id  = b.id
WHERE a.id IN (
	SELECT a.foo, a.bar from a
	INNER JOIN b on a.b_id  = b.id
)
LIMIT 30;
```

If a or b contains millions of rows, this will cause a severe performance hit as the inner query will fetch ALL matching results instead of just 30.

I'm not really sure how to fix this one, as limiting the inner query may result in different orderings as mentioned in the referred ticket.

Maybe the original use case of the extension (fetching a full set of children even if there are filters applied on them) should be an optional feature. Or it needs a completely different implementation. The cost for it is too high performance-wise imo.
