### ISSUE TITLE
cache_headers operation option ignores etag value.

### ISSUE THREAD

**Issue by jdelaune** [api-platform/core#4280]
**API Platform version(s) affected**: 2.6.4

**Description**  
Endpoint always added an etag header.

**How to reproduce**  
```
#[ApiResource(
    collectionOperations: ['get' => [
            'cache_headers' => ['max_age' => 0, 'shared_max_age' => 0, 'etag' => false],
        ],
    ],
)]
```

However I get an etag header in the response.

**Comment by soyuka** [comment]
This bug is targeting 2.7, as API Platform 3.2 is out, version 2.7 has reached end of life. Therefore we'll close this issue. 

We recommend to upgrade to API Platform 3.0, [Les-Tilleuls.coop](contact@les-tilleuls.coop) can offer paid support to help or even migrate your projects if they have tests. 

We want to fund a Long Term Stable version of API Platform, if you or your organization would like to contribute to LTS support, please visit our [Open Collective crowdfunding](https://opencollective.com/api-platform/projects/27-lts).
