### ISSUE TITLE
PUT on /resource/non-existing-id should work according to the HTTP spec

### ISSUE THREAD

**Issue by soyuka** [api-platform/core#4344]
See https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.4 

probably using `merge` in Doctrine.

**Comment by rugolinifr** [comment]
Do you mean that the request must _create_ if it does not exist ?

If so, I am a bit worried:

- How to handle `security` ? for example, the current user is not allowed to POST the resource, but is allowed to PUT. What security rule/ voter  is applied when the _identified_ resource does not exist ?

- How will behave `security` and `security_post_denormalize` keywords ?

- What if the _identified_ resource exists within the persistence storage, but it's excluded by the data provider because of some `QueryItemExtensionInterface` ?

- What about resources with different denormalization groups on POST and PUT requests ? For example when you define a property at creation that can't be updated after ?

thanks in advance for your answer

**Comment by dunglas** [comment]
Basically our current `PUT` implementation behaves more or less like a `PATCH`. The idea here, now that `PATCH` is properly supported (that wasn't the case initially), is to respect the true semantic of the PUT request and to encourage to use `PATCH` for the use cases you describe.

To prevent any BC break, we plan to introduce a new attribute in 2.7 (set to false by default, but triggering a deprecation warning is not set to true) to enable the standard behavior (if set to false, the current behavior will be preserved). In 3.0 we'll remove the non-standard behavior.

**Comment by rugolinifr** [comment]
Ok I see. I'll take a look at the PATCH method then.

Thanks

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/4996
