### ISSUE TITLE
Support Symfony 6.0

### ISSUE THREAD

**Issue by dunglas** [api-platform/core#4543]
Now that we support Symfony 5.4, we must also support Symfony 6.0.

* [ ] Checkout the 2.6 branch
* [ ] Add  allow the `^6.0` version for all Symfony projects
* [ ] Run the test suite
* [ ] Remove the annoying type hints from Symfony's interfaces (open PR and ping me)

**Comment by leeroynico** [comment]
I work on it

**Comment by Chris53897** [comment]
This ticket is not so easy. I will try to help with this.
I think 2 steps are necessary in my point of view. 

1. Build a Pipeline and allow symfony 6 in dependencies to get an overview of how much work is needed to support symfony 6.
2. Decide if APIP 2.x needs support for Symfony 6. Or only APIP 3.x with PHP8. Because you can not make a project compatible with Symfony 6 if you do not require Php >8. At least i do not know a way to do this.


To 1)

The CI Pipeline will not test all symfony 6 packages. Symfony 6.0 needs to be added to the test-matrix on 2 places (this allows the 2 additional packages to be tested against 6.0. [Example Test-Run](https://github.com/Chris53897/core/runs/4194724799?check_suite_focus=true)

Some symfony components are sticked to 5.4 because of dependencies. 
(The link mink-repo is merged now, but the tests are not covering symfony 6.)

Example
`composer why symfony/browser-kit`

...
friends-of-behat/mink-browserkit-driver  v1.5.0    requires     symfony/browser-kit (^4.4|^5.0)

I made a [PR draft](https://github.com/FriendsOfBehat/MinkBrowserKitDriver/pull/10)
and will try to update b).
a) Origin https://github.com/minkphp/driver-testsuite
b) Fork von oberen https://github.com/FriendsOfBehat/driver-testsuite (is used in friends-of-behat/mink-browserkit-driver)

**Comment by Chris53897** [comment]
update:
One blocker is gone. 
Here i wait for a new release.
https://github.com/minkphp/Mink/pull/814

After that "soyuka/contexts" could be updated too.

Now that 6.x is stable the CI Tests should be easier.
