### ISSUE TITLE
PDF custom format is not supported

### ISSUE THREAD

**Issue by abderahmaneBasil** [api-platform/core#4829]
Hello everyone, I have difficulties implementing a custom format for PDF content. I am always receiving this error despite following api-platform doc :
`Serialization for the format \"pdf\" is not supported.`

What I have at the moment is a DataOuputTransformer which transform my entity to a PDF so I get a Response with Content-type : application/pdf (using WeasyPrint).

I set a specific custom endpoint with an output_formats. The DTO just contain a string for the Url of the PDF.
```
'receipt' => [
            "method" => "GET",
            "status" => 200,
            "input" => false,
            "output" => DeliveryNote::class,
            "output_formats" => [
                "pdf" => ["application/pdf"]
            ],
            "path" => "/livraisons/{id}/receipt",
            "openapi_context" => [
                "summary" => "Export in PDF a delivery note.",
                "description" => "Export in PDF a delivery note."
            ]
        ]
```

I created a Serializer from doc example but it seems to not be used :/
```
# api/config/services.yaml
services:
    App\Serializer\DeliveryNoteNormalizer:
        arguments: [ '@api_platform.serializer.normalizer.item' ]
```

```
<?php
// api/src/Serializer/DeliveryNoteNormalizer.php

namespace App\Serializer;

use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class DeliveryNoteNormalizer implements NormalizerInterface, DenormalizerInterface
{
    private $normalizer;

    public function __construct(NormalizerInterface $normalizer)
    {
        if (!$normalizer instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException('The normalizer must implement the DenormalizerInterface');
        }

        $this->normalizer = $normalizer;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        return $this->normalizer->denormalize($data, $class, $format, $context);
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $this->normalizer->supportsDenormalization($data, $type, $format);
    }

    public function normalize($object, $format = null, array $context = [])
    {
        return $this->normalizer->normalize($object, $format, $context);
    }

    public function supportsNormalization($data, $format = null)
    {
        return $this->normalizer->supportsNormalization($data, $format);
    }
}
```

When the pdf format is registered globally in api_platform.yaml, swagger is giving the same error while loading :
`Serialization for the format \"pdf\" is not supported.`

Do you have some idea what could be the problem and how to make it works ?
Thank you !

**Comment by Eliepse** [comment]
Hello,

I'm not sure to understand how you implemented the PDF conversion. But it looks like you used the DataTransformer to convert you entity into a PDF file. The thing is DataTransformer is here to transform an object, and return an object. You cannot return a value that is not an simple object. This object is used to help the serializer to create the expected output (transform some values, add more fields or whatever).

I think at the end, you are sending a PDF File to a serializer that tries to output JSON or so. Your problem might require to create a dedicated normalizer if you need to replicate the behavior at large scale. Otherwise, I would suggest your to create a custom controller to handle your route. The docs provide an example with a custom "NotFoundController" at the end of [this section](https://api-platform.com/docs/core/operations/#enabling-and-disabling-operations).

**Comment by soyuka** [comment]
data transformers are deprecated, please use a processor using 3.0 metadata.
