### ISSUE TITLE
Eager fetch associations by path instead of #[Group]

### ISSUE THREAD

**Issue by iluuu1994** [api-platform/core#4914]
**Description** 

We're using api-platform very successfully using `#[Group]`s and `#[GroupFilter]`s to fetch associations. This works for the majority of cases but has one significant limitation: Infinite recursion and overfetching.

**Example**  

#### Infinite recursion

Normally, infinite recursion can be avoided by using a custom `#[Group]` for an association that should not be eager fetched. However, this doesn't work for all cases, particularly when your entity appears twice in the entity hierarchy you're trying to retrieve.

```php
class Contract {
	#[Group('contract')]
	public string $title;

	#[Group('contract_aliases')]
	public array $aliases;
}

class ContractAlias {
	public Contract $newContract;

	#[Group('alias')]
	public Contract $oldContract;
}
```

The Doctrine annotations are omitted for brevity. The exact business logic is not important. We're trying to get the `Contract` entities along with the contracts it replaces, but *not the contracts the replacements replace*. There' no way to currently specify this. If we pass the `contract`, `contract_aliases` and `alias` groups api-platform will infinitely try to join `contract.aliases` and then `alias.oldContract`.

What we'd really like is to specify a join list with absolute paths. Something like `['aliases', 'aliases.oldContract']`.

#### Overfetching

```php
class Contract {
	#[Group('contract')]
	public string $title;

	#[Group('contract_organization')]
	public string $organization;

	#[Group('contract_aliases')]
	public array $aliases;
}

class ContractAlias {
	public Contract $newContract;

	#[Group('alias')]
	public string $oldOrganization;
}

class Organization {
	#[Group('organization)]
	public string $title;

    // Lots of things
}
```

In our business logic, `Contract` has a n:1 relation to `Organization`s. We avoided the recursion issue by linking the organization instead of the `Contract`. This has some negative implications (we don't know what the original `Contract` was) that we can live with.

However, even without infinite recursion the relative `#[Group]`s lead to an overfetching issue. In this particular case, we want to load additional relations (`contract.organization.*`) of the root entities but not the `oldOrganization` of the aliases where only really the title is required. Since our contracts can have n aliases, and for each of those all those entites are fetched again this results in a ~5 slowdown for our query, which is unfortunate because we never actually use this data.

Just like above, a join list with absolute paths could do the trick. So for this case  `['aliases', 'aliases.oldOrganization', 'organization', 'organization.additionalStuff']`.

### Implementation

I know very little about how api-platform works. I understand that this is probably not a simple task. I might be able to negotiate some time from our client to implement something. To increase the chances of success I'd be very happy about some pointers on how this could be best achieved.

Thanks for your response!

**Comment by soyuka** [comment]
For complex use cases you should implement your own [state provider](https://api-platform.com/docs/main/core/state-providers/). Also you may be interested in reading the Symfony's Serializer documentation where you may found more options to help you with that case.

**Comment by iluuu1994** [comment]
This is something that is currently not possible with the RAD approach, so I don't know why this is categorized as support. While I understand that RAD is not the most bullet proof approach it is the one we're currently taking due to a strict deadline, and it works very well for the most part. This is one of the only limitations we've run into. So I was essentially asking for the best approach to implement this feature in API-Platform to contribute.

The Serializer currently only supports `AbstractNormalizer::ATTRIBUTES` (which API-Platform is already using for the `PropertyFilter`) but it essentially does the opposite of what we need, filter properties *out* of the result set. The data it still fetched from the database, and you'll also need to specify every single field in the result set.

I created https://github.com/symfony/symfony/issues/47510 and I will probably just give it a shot. Regardless, API-Platform will probably need at least some changes to properly support it if it makes it into Symfony Serializer.

**Comment by jamesisaac** [comment]
This is something I've run into too, and while it would be great to see a solution, I have a feeling that any solution would probably be too high a complexity level to sit nicely with what APIP is trying to do with its RAD tools.

It seems like biggest changes needed would be in the Serializer (addressable with the issue you opened against Symfony), the Doctrine query generation, and the OpenAPI schema generation.  I have a suspicion the OpenAPI schema type names would get pretty unwieldy with the `paths` approach being proposed.

Interestingly GraphQL, which APIP also supports, was invented to solve pretty much exactly this overfetching problem.  So I suppose an argument would be that you should just use that for giving the user such fine-grained control over which paths to fetch, rather than attempting to reinvent it on REST.  Or if you want control on the DB fetching just from the server-side, I suppose the argument there is that the new APIP State Providers are extremely flexible for this.

I've basically come to accept that the APIP REST RAD tools make for extremely efficient development in 90% of cases, but do have their limitations, which are probably necessary to keep the architecture straightforward.  So in cases where you hit that limit, you either have to restructure serializer groups to make it fit, or spend the extra time on custom State Providers / DTOs.
