### ISSUE TITLE
Missing interface after minor upgrade

### ISSUE THREAD

**Issue by OskarStark** [api-platform/core#4991]
**API Platform version(s) affected**: x.y.z
I am on version 2.6.8

**Description**  
The interface `ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface` was present in `2.6.8` but hard moved in `2.7.0` to `ApiPlatform\Doctrine\Orm\Util\QueryNameGeneratorInterface`.
It is easy to fix, but it looks like a BC break to me. The interface was not experimental or internal.

Checking the CHANGELOG, the `Core` namespace was removed in 3.0 beta 🤔 not in 2.7.0

**How to reproduce**  

**Possible Solution**  
Add it back with a deprecation

**Additional Context**

**Comment by soyuka** [comment]
it is aliased and deprecated: https://github.com/api-platform/core/blob/2.7/src/deprecated_interfaces.php#L37

**Comment by yobrx** [comment]
Hi @soyuka & @OskarStark ,

The service is aliased, but I think @OskarStark implements a class with this interface.

**Comment by soyuka** [comment]
Are you using autowiring and we forgot an alias?

**Comment by aelfannir** [comment]
Facing the same issue after 2.7.0 migration

**Comment by OskarStark** [comment]
> The service is aliased, but I think @OskarStark implements a class with this interface.

Exactly and it does not have the "hack" like other classes with the `class_exists` wrapper

**Comment by usu** [comment]
Similar happened to me for this interface:
`ApiPlatform\Core\Api\UrlGeneratorInterface`

which was hard moved in 2.7 to 
`ApiPlatform\Api\UrlGeneratorInterface`

**Comment by OskarStark** [comment]
Yes same for me in another project

**Comment by bytecast-de** [comment]
The `ApiPlatform\Core\Bridge\Doctrine\Orm\Util\QueryNameGeneratorInterface` is used inside the `ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\FilterInterface` and throughout all classes using the FilterInterface. Since it was moved, these are now importing an undefined class. Although that might "work" because of aliasing, you will get an error from your IDE, e.g. when implementing a custom filter.

So adding it back with a deprecation, as @OskarStark already pointed out, should fix this issue.
