### ISSUE TITLE
[2.7] Class "ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\ConstantScoreFilterExtension" not found

### ISSUE THREAD

**Issue by darthf1** [api-platform/core#5005]
When upgrading `2.6.8` to `2.7.0` and running my existing test suite, I get the following error:

```
Error : Class "ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\ConstantScoreFilterExtension" not found
 /home/www/app/var/cache/test/ContainerOSOLgNS/getApiPlatform_Elasticsearch_RequestBodySearchExtension_ConstantScoreFilterService.php:20
 /home/www/app/var/cache/test/ContainerOSOLgNS/Infrastructure_Shared_Symfony_KernelTestDebugContainer.php:860
 /home/www/app/var/cache/test/ContainerOSOLgNS/getApiPlatform_Elasticsearch_CollectionDataProviderService.php:23
 /home/www/app/vendor/api-platform/core/src/Core/Bridge/Elasticsearch/DataProvider/CollectionDataProvider.php:120
 /home/www/app/src/Infrastructure/Shared/ApiPlatform/DataProvider/SubresourceDataProvider.php:48
 /home/www/app/vendor/api-platform/core/src/Core/Bridge/Symfony/Bundle/DataProvider/TraceableChainSubresourceDataProvider.php:63
 /home/www/app/vendor/api-platform/core/src/Core/DataProvider/OperationDataProviderTrait.php:90
 /home/www/app/vendor/api-platform/core/src/Core/EventListener/ReadListener.php:130
 /home/www/app/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115
 /home/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php:230
 /home/www/app/vendor/symfony/event-dispatcher/EventDispatcher.php:59
 /home/www/app/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:153
 /home/www/app/vendor/symfony/http-kernel/HttpKernel.php:129
 /home/www/app/vendor/symfony/http-kernel/HttpKernel.php:75
 /home/www/app/vendor/symfony/http-kernel/Kernel.php:202
 /home/www/app/vendor/symfony/http-kernel/HttpKernelBrowser.php:65
 /home/www/app/vendor/symfony/framework-bundle/KernelBrowser.php:172
 /home/www/app/vendor/symfony/browser-kit/AbstractBrowser.php:370
 /home/www/app/vendor/api-platform/core/src/Symfony/Bundle/Test/Client.php:122
```

**Comment by rendler-denis** [comment]
Having the same issue and switching to the new interfaces and classes is way longer than we have time right now.
I also found this:
![image](https://user-images.githubusercontent.com/1212958/191957833-fefea177-b0f5-4bc8-a620-2c1a4958ed57.png)

I see two issues with this:
1) the new class is `final` and thus cannot be extended
2) how should the class be made available since the condition of `false` will never allow PHP to execute that code?

Any help is appreciated. Thanks

**Comment by soyuka** [comment]
This is how we managed to deprecate the old namespace, it should work without hassle.

**Comment by rendler-denis** [comment]
hey @soyuka . 
thanks for the reply. 
what I found is that the system triggers the autoloading and the problem is that the if will always be false. so, the class will never be defined. this in turn will trigger a class not found exception and everything will end there.
also, looking at the code, even if the if would be triggered the new class is also a final class, thus it cannot be inherited.

**Comment by soyuka** [comment]
it's a hack we use and that works if you've an issue with autowiring or a php error let me know we don't cover IDE issues.

**Comment by darthf1** [comment]
@soyuka this is not an IDE issue, but a real runtime issue. As explained by @rendler-denis it happens with autoloading, and in my case the error is also triggered by my test suite.

**Comment by rendler-denis** [comment]
> it's a hack we use and that works if you've an issue with autowiring or a php error let me know we don't cover IDE issues.

hey, @soyuka 

I do not understand what do you mean by IDE issue? 
My issue is during runtime. And my question was how is the if triggered? if it is something in my code I am really glad to change it, but can't seem to find out how to trigger the if.
the second issue I found is that the class that is defined inside the if extends a class that is marked as final. as far as I know PHP does not allow that.
I am trying to understand if this is a bug so that we can report it as such or I am doing something terribly wrong. I am just seeking for some advice not trying to cast stones.

**Comment by soyuka** [comment]
Please send me a reproducer. All the classes and interfaces that are mentioned here have aliases. We fixed some of them we forgot and they're available in the new 2.7.1 version. Please update and let me know how I can help. 

@rendler-denis unless I have a typo in the class names you're showing here there's no issue on our end. What is your runtime error and how can I reproduce?

> the second issue I found is that the class that is defined inside the if extends a class that is marked as final. as far as I know PHP does not allow that.

This is done on purpose in our code to trick the php namespace behavior in thinking the class is correctly defined. We're aliasing the class using [class-alias](https://www.php.net/manual/en/function.class-alias.php).

**Comment by epinxteren** [comment]
The file: [ttps://github.com/api-platform/core/blob/2.7/src/deprecation.php#L442](https://github.com/api-platform/core/blob/2.7/src/deprecation.php#L442) says that the classes is deprecated.

`
// These classes are deprecated but we don't want aliases as the interfaces changed
$deprecatedClassesWithoutAliases = [
   ...
    ApiPlatform\Core\Bridge\Elasticsearch\DataProvider\Extension\ConstantScoreFilterExtension::class => ApiPlatform\Elasticsearch\Extension\ConstantScoreFilterExtension::class,
...

`

Any ideas how to use elasticsearch in 2.7?

**Comment by darthf1** [comment]
@soyuka, apologies for the delay, please find the reproducer [here](https://github.com/darthf1/api-platform-reproducer).

When creating the reproducer, I noticed the error started when I requested a sub-resource URL. Since there is no subresource provider for elasticsearch, I created my own [DataProvider](https://github.com/darthf1/api-platform-reproducer/blob/master/src/ApiPlatform/DataProvider/MyCollectionDataProvider.php) which re-uses the elasticsearch collection provider.

**Comment by darthf1** [comment]
If there's a solution requiring changing something on my end, without migrating to the new metadata system, I'm open for suggestions :)

**Comment by darthf1** [comment]
friendly ping @soyuka. Would love to get started on the v2.7 to v3 migration :)

**Comment by darthf1** [comment]
@soyuka @alanpoulain @dunglas anyone?

**Comment by MotAtlas** [comment]
Any news on this?

**Comment by darthf1** [comment]
https://github.com/api-platform/core/pull/5283 fixed the issue for me!

Thanks a lot @vincentchalamon
