### ISSUE TITLE
Refactor denormalization process?

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/core#528]
Since symfony/symfony#17660 it looks like we can have a cleaner denormalization process.

Perhaps we will have the following denormalizers:
- ResourceDenormalizer
- ResourceCollectionDenormalizer

@dunglas Please correct me if I'm thinking of this the wrong way.

**Comment by dunglas** [comment]
you're right

**Comment by teohhanhui** [comment]
@dunglas See https://github.com/api-platform/core/pull/415#issuecomment-226470499

If for example I have a `libphonenumber\PhoneNumber` field (converted via a Doctrine custom type) inside a Doctrine Embeddable, it is not reachable by the normalization/denormalization process.

**Comment by dunglas** [comment]
@teohhanhui After re-reading this issue, I'm not sure of what you mean exactly.

> If for example I have a libphonenumber\PhoneNumber field (converted via a Doctrine custom type) inside a Doctrine Embeddable, it is not reachable by the normalization/denormalization process.

It should be ok because we delegate the denormalization to the Symfony's `AbstractObjectNormalizer` (https://github.com/api-platform/core/blob/master/src/JsonLd/Serializer/ItemNormalizer.php#L131) and this class will call the applicable normalizer for the given type: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L261

The only problem I can see is when the custom type is inside a raw array. For this case, we should probably do something like this: https://github.com/dunglas/doctrine-json-odm/blob/master/src/Normalizer/ObjectNormalizer.php#L72-L76

**Comment by dunglas** [comment]
@teohhanhui any update?

**Comment by teohhanhui** [comment]
@dunglas We're not passing the `$propertyTypeExtractor` argument to `AbstractObjectNormalizer`. Shouldn't we take advantage of the whole recursive denormalization instead of doing it on our own? That's what I meant in the first comment.

**Comment by dunglas** [comment]
I've tried to do that but it's not possible with the current implementation of the Serializer (it requires at least to make the method `validateAndDenormalize` protected.
I want to release the v2 soon (before Symfony 3.2), so I suggest to keep this as is and refactor it when some extensions points to the Serializer will be added.

**Comment by soyuka** [comment]
Closing in favor of https://github.com/api-platform/core/pull/2579
