### ISSUE TITLE
api_platform.metadata.property.identifier_metadata_factory is not cached

### ISSUE THREAD

**Issue by MariusJam** [api-platform/core#5285]
**API Platform version(s) affected**: 3.0.8

**Description**  

As stated in #4975 (this [comment](https://github.com/api-platform/core/issues/4975#issuecomment-1353517246)), the service `api_platform.metadata.property.identifier_metadata_factory` (which is suggested to be removed in 3.0 by a TODO comment) has no cache associated with it.

This leads to cache warmup being longer as the service is call again and again. 

After a bit of investigation, I'm wondering whether this wasn't the orginal purpose of `api_platform.cache.identifiers_extractor` which is sent as argument to `api_platform.cache_warmer.cache_pool_clearer` in events.xml but which seems to be **actually inexistent**.

**How to reproduce**  

`bin/console cache:warmup`

**Possible Solution**  

Configure a cache for `api_platform.metadata.property.identifier_metadata_factory`, possibly by restoring `api_platform.cache.identifiers_extractor`

**Comment by soyuka** [comment]
Probably because https://github.com/api-platform/core/blob/2.6/src/Api/CachedIdentifiersExtractor.php was removed in 3.x.. 

The series of `metadata.property.identifier_metadata_factory` is there to avoid a circular dependency injection within PropertyMetadataFactories. We could probably add a cache layer for them by duplicating this declaration: 

https://github.com/api-platform/core/blob/main/src/Symfony/Bundle/Resources/config/metadata/property.xml#L26 

PR welcome.
