### ISSUE TITLE
Feature Request(BC?): Populate Request->query with uriTemplate/uriVariables values

### ISSUE THREAD

**Issue by Richard87** [api-platform/core#5299]
**Description**  
After upgrading to 3.0 i noticed the path variables are no longer available in the Request->query part as I expected.

**Example**  
```php
        $partnership = $request->query->get('id'); 
        // instead i have to do this: $request->attributes->get('id');
```

A really minor thing, but it would be one less thing to think about, and personally I think it makes sense that uri variables are available in the query object:)

If you agree, I would love to help out and create a PR

**Comment by nesl247** [comment]
I don't represent api-platform, but I doubt they would add this in. The `id` isn't part of the query string, which the `query` property represents. It's part of the path, which I don't believe Symfony handles in the `Request` as a parameter bag at all. That's why `attributes` is the correct place for this.

**Comment by Richard87** [comment]
I'm closing this for the team to focus on way more exciting things ;)
