### ISSUE TITLE
Split into multiple components

### ISSUE THREAD

**Issue by ghost** [api-platform/core#5357]
api-platform/core is a library according to composer.json, but a "composer require" makes modifications to your application code (currently it adds a route the config and adds the ApiResource class to your src directory) as Symfony Flex executes a recipe for the embedded bundle.

Having changes made to your application automatically is undesirable when installing a standalone library. In my opinion the bundle should be a separate package to allow the api-platform/core library to be used without any undesired side effects.

https://github.com/symfony/recipes/pull/1168

**Comment by dunglas** [comment]
Everything as been designed to support splitting this main repository in subtree splits (as Symfony). The remaining part are creating the CI pipeline to do that (and test it), and adding the needed `composer.json` files.

TBH, this isn't our priority right now because Symfony is the only framework with official support, but when we'll add support for other frameworks will work on that.

That being said, as usual, contributions are welcome if you want to work on this.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/5434 started at some point the bundle will be splitted as well

**Comment by soyuka** [comment]
#5535 #5532 #5526 #5529 #5530 then the Symfony bridge then add a deprecation script as we're moving some classes. if state isn't published its a mistake.
