### ISSUE TITLE
Response description is not changable when using openapi

### ISSUE THREAD

**Issue by sajixavier** [api-platform/core#5381]
**API Platform version(s) affected**: 3.1.1

**Description**  

With this new version, it seems impossible to change the response description for a given status.

**How to reproduce**  

Define an ApiResource with a Put operation like this (might be same for other operations)

```
new Metadata\Put(
            status: 200,
            openapi: new Model\Operation(
                summary: 'Test summary',
                responses:[
                    '200' => new Model\Response(
                        description: 'Custom response message'
                    )
                ],
            ),
        )
```
In swagger documentation description is shown as '(Resource name) resource updated'

**Additional Context**  

Symfony: 6.2.5
PHP: 8.1

**Comment by Byidi** [comment]
You can change responses descriptions using `openapiContext['responses'`:

```php
#[Put(
    openapiContext: [
        'responses' =>  [
            200 => [
                'description' => 'Custom response message',
            ]
        ]
    ]
)]
```

**Comment by soyuka** [comment]
We're working on supporting the `openapi`, `openapiContext` is deprecated ;)

**Comment by HuyNguyen206** [comment]
hi @soyuka, regarding api platform, I can't find the document that describe how to use openapi, openapiContext option so It is quite difficult to custom the response, and description in the Swagger documentation. Could you show me how to use these options? Thank you

**Comment by Zenifica** [comment]
same than @HuyNguyen206

**Comment by monitaurus** [comment]
> hi @soyuka, regarding api platform, I can't find the document that describe how to use openapi, openapiContext option so It is quite difficult to custom the response, and description in the Swagger documentation. Could you show me how to use these options? Thank you

It's not a long detailed documentation, but here's a quick guide on how to use `openapi`: [Extend OpenAPI Documentation
](https://api-platform.com/docs/guides/extend-openapi-documentation/)

An interesting part here is that we can manipulate objects rather than array.
It reduces errors and enhances a lot the self discoverability of what we can set.

But, there's this line in the documentation:
> When a field is not specified API Platform will add the missing informations.

It seems valid only for the argument within the Operation level.
In my case, I tried to only set the description of a request body, like this:
```php
    openapi: new Operation(
        requestBody: new RequestBody(
            description: 'Description'
        )
    )
```
The operation's description, the parameters, the responses, ... all is filled up by API Platform.
But as the `requestBody` is a new instance, it replaces the whole request body, including the automatically generated example and schema, even if I wanted to change only the description.
More coding details in this issue: https://github.com/api-platform/api-platform/issues/2567#issuecomment-2024885828

The solution is to [decorate the OpenApiFactory](https://api-platform.com/docs/core/openapi/#:~:text=Overriding%20the%20OpenAPI%20Specification) to avoid this.

_cc @HuyNguyen206, @Zenifica_
