### ISSUE TITLE
Improve serializer performance with getSupportedTypes

### ISSUE THREAD

**Issue by Oipnet** [api-platform/core#5610]
**Description**  
Symfony 6.3 add getSupportedTypes to improve serializer performance.

**Example**  
Read this article : https://symfony.com/blog/new-in-symfony-6-3-performance-improvements#improved-performance-of-serializer-normalizers-denormalizers

**Comment by burned42** [comment]
Just to have this noted down here, this is not only about improving performance, but since not implementing the `getSupportedTypes` method is deprecated since symfony/serializer 6.3, my deprecation log get flooded with those deprecation messages so much that I had to turn the deprecation log of so it doesn't fill up my disk :D

**Comment by mvhirsch** [comment]
Since #5672 got merged and [3.1.13](https://github.com/api-platform/core/releases/tag/v3.1.13) got released last week, I think we can close this?

**Comment by Renrhaf** [comment]
Excellent thank you ! Deprecation logs are gone after upgrading and adapting our own normalizers :)
