### ISSUE TITLE
LexikJWTAuthentication bridge

### ISSUE THREAD

**Issue by polc** [api-platform/core#563]
What about a LexikJWTAuthenticatio bridge to allow credentials to be sent as JSON object (FOSRestBundle support it).

See : https://github.com/lexik/LexikJWTAuthenticationBundle/issues/123#issuecomment-173860682

**Comment by dunglas** [comment]
Why not, but IMO a converter from JSON to form encoded is a bad implementation. I would prefer a security listener dealing directly with the JSON object like https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/UsernamePasswordFormAuthenticationListener.php but parsing the JSON directly.

IMO such listener should be in the bundle from Lexik or in Symfony core, not in API Platform core (because it can be useful in other cases, like when using a pure SF app). What do you think @slashfan.

**Comment by dunglas** [comment]
See https://github.com/symfony/symfony/pull/18952. Tests and feedback are welcome!

Closing this one, please comment on the Symfony PR.
