### ISSUE TITLE
Invalid IRI generation when using GetCollection::itemUriTemplate and multiple identifiers

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/core#5662]
**API Platform version(s) affected**: 3.x

**Description**
Considering the following operations:
```php
new GetCollection(
    routePrefix: '/admin'
),
new Get(
    routePrefix: '/admin'
),
new GetCollection(
    uriTemplate: '/books/{bookId}/reviews{._format}',
    uriVariables: [
        'bookId' => new Link(toProperty: 'book', fromClass: Book::class),
    ],
    itemUriTemplate: '/books/{bookId}/reviews/{id}{._format}'
),
new Get(
    uriTemplate: '/books/{bookId}/reviews/{id}{._format}',
    uriVariables: [
        'bookId' => new Link(toProperty: 'book', fromClass: Book::class),
        'id' => new Link(fromClass: Review::class),
    ],
),
```
On `GET /books/{bookId]/reviews`, an error occurred while trying to generate the IRI of each member because of missing `bookId` parameter.

**Possible Solution**
Do not use `$identifiersExtractorOperation` variable in `ApiPlatform\Symfony\Routing\IriConverter`.

**Context**
Introduced in https://github.com/api-platform/core/pull/5176

**Comment by soyuka** [comment]
It should find the parameter there's something wrong in extracting identifiers then?

**Comment by paullallier** [comment]
I think I'm seeing something related to this, though I'm not certain it's not a different bug.  I have an ApiReposes which includes these operations:
```
		new Get(
			uriTemplate: '/user_permissions/{userUuid}.{_format}',
			uriVariables: ['userUuid' => new Link(fromClass: self::class, identifiers: ['userUuid'], compositeIdentifier: false)],
			requirements: ['userUuid' => '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'],
			provider: UserPermissionStateProvider::class,
			<snip extra lines>
		),
		new Get(
			uriTemplate: 'user_permissions/set/{setId}.{_format}',
			uriVariables: ['setId'],
			provider: UserPermissionSetStateProvider::class,
			<snip extra lines>
		),
		new GetCollection(
			uriTemplate: 'user_permissions/set.{_format}',
			provider: UserPermissionSetStateProvider::class,
			itemUriTemplate: 'user_permissions/set/{setId}.{_format}',
			<snip extra lines>
		),

**Comment by paullallier** [comment]
I think I'm seeing something related to this, though I'm not certain it's not a different bug.  I have an ApiReposes which includes these operations:
```
		new Get(
			uriTemplate: '/user_permissions/{userUuid}.{_format}',
			uriVariables: ['userUuid' => new Link(fromClass: self::class, identifiers: ['userUuid'], compositeIdentifier: false)],
			requirements: ['userUuid' => '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'],
			provider: UserPermissionStateProvider::class,
			<snip extra lines>
		),
		new Get(
			uriTemplate: 'user_permissions/set/{setId}.{_format}',
			uriVariables: ['setId'],
			provider: UserPermissionSetStateProvider::class,
			<snip extra lines>
		),
		new GetCollection(
			uriTemplate: 'user_permissions/set.{_format}',
			provider: UserPermissionSetStateProvider::class,
			itemUriTemplate: 'user_permissions/set/{setId}.{_format}',
			<snip extra lines>
		),
```

When I make my GET request to user_permissions/set, the ItemNormalizer sets `$context['item_uri_template']` to the value from the itemUriTemplate field, it calls IriConverter::getIriFromResource(), which finds the correct Get operation (the second one in the list above), but then calls IriConverter::generateSymfonyRoute() which uses the default (first) Get operation to determine the uriVariables for the IRI.  It then tried to build the IRI based on the itemUriTemplate operation but can't find the setId, because it's expecting the uriVariables the userUuid.

If I replace setId with userUuid, in the second Get operation and the itemUriTemplate field, it starts to work.

I think the test harness uses {id} for the custom itemUriTemplate test case, which is why it's passing.

**Comment by paullallier** [comment]
Sorry Vincent's PR fixes it for me - I'll just wait for it to be merged.  I should have checked that first.
