### ISSUE TITLE
Add support for custom methods

### ISSUE THREAD

**Issue by lyrixx** [api-platform/core#5679]
**Description**  

ATM, it's not really documented, and It's not really supported to use custom method for a resource.
Example: 

```php
#[ApiResource(operations: [
    new  HttpOperation(
        method: 'LINK',
    ,
])]
class A
```

This create a the routes, but not the OpenAPI Documentation
BTW, the class seems quite [limited to some methods](https://github.com/api-platform/core/blob/main/src/OpenApi/Model/PathItem.php#L41-L79)

Finally, If I use:

```php
#[ApiResource()]
#[HttpOperation(method: 'LINK')]
class A
```

it does not work at all

**Comment by mrossard** [comment]
Does OpenApi actually support this? In the specs i only see the same exact HTTP verbs you linked as possible options for the operations in the Path Item object.

Adding custom operations might be doable, but seems like a lots of custom work left to the dev anyway, and if the openapi specs don't support them you'd have to document them some other way anyway...?

**Comment by lyrixx** [comment]
Oh! I didn't know that. It's not cool for open API.

But the first issue remains

**Comment by mrossard** [comment]
I'm actually wondering whether adding custom operations would be a plus for the DX...what would the framework actually help with? 

If the framework has no way to know what the operation is supposed to do, it can't automatically do much, and since it can't include them in the docs either aren't you just better off implementing your custom operations with classic symfony controllers?

**Comment by lyrixx** [comment]
I we consider that OpenAPI documentation for custom operation cannot be implemented, APIP works as expected, expect the for the second example I gave.

**Comment by mrossard** [comment]
> I we consider that OpenAPI documentation for custom operation cannot be implemented, APIP works as expected, expect the for the second example I gave.

well what would you expect the second example to do?

**Comment by lyrixx** [comment]
The same as the first example

**Comment by mrossard** [comment]
which is, just create routes? I don't get the point, to be honest...then what? You add a custom symfony controller? Then why not directly attach your route to that controller?

**Comment by lyrixx** [comment]
I don't understand what you missed 😬 

Using custom controller [is discouraged ](https://api-platform.com/docs/core/controllers/).

Using an attribute it how we configure all other endpoint. So I expect it does exactly the same than an PUT endpoint for example

1. read from the request
2. find the object from a provider
3. hydrate
4. persist
5. serialize, back

Of course, only if configured

**Comment by mrossard** [comment]
Well yes it is discouraged, wwhich is why i suggested just using a symfony controller for such use cases since the framework can't do much to help anyway.... 

Not all operations require a provider / expect anything to get persisted, or event expect any payload in the request or response at all. And with a custom operation the framework has no way to know what this specific operation requires!

You'd have to be able to specify whether the operation needs to call the provider (read: true could do that) and whether it should try to persist something. Afaik this is triggered by the specific operations that are meant to change the object's state, so a way to Yell the framework that this operation does would need to be added.
You'd also need to specify if there's a payload to read, a payload to return, what HTTP code to return on success, etc...you're pretty much just using a simple symfony controller at this point.

**Comment by lyrixx** [comment]
I'll have to re-implement many things by hand, too bad. But I understand your POV, so let's close this issue.

**Comment by dunglas** [comment]
For the record, I'm in favor of supporting custom methods. They aren't supported by OpenAPI but they are by the HTTP spec.

**Comment by mrossard** [comment]
> I'll have to re-implement many things by hand, too bad. But I understand your POV, so let's close this issue.

That's indeed just my POV though, I'm not sure you want to close this as other points of view could be expressed by others.

> For the record, I'm in favor of supporting custom methods. They aren't supported by OpenAPI but they are by the HTTP spec.

For example, one pretty important voice on the matter :D 

And I'm actually pretty curious about that. The number of available HTTP verbs is pretty limited afaik, would you just want to support all of those with predefined behaviors, or would you want to even allow adding custom ones?

**Comment by dunglas** [comment]
The RFCs allow registering extra HTP methods. There is even an IANA registry listing standardized ones: https://www.iana.org/assignments/http-methods/http-methods.xhtml

The standard doesn't forbid using custom methods (even if it's usually considered bad practice), so I would be in favor of being lax and allow any string to be used.
