### ISSUE TITLE
Bug Swagger after update Api Platform 

### ISSUE THREAD

**Issue by Magali71** [api-platform/core#5904]
**API Platform version(s) affected**: v3.2.1 (api-platform/core)

**Description** 
On the Api Paltform Doc when  Try it Out I have a 503. When I look at the url I see that it's not the right one.  
instead of https://mysite.net/thing/things I have https://mysite.net/things. The base of the url has been removed. 
this happened when I updated api Platform 

**How to reproduce**  

**Possible Solution**  

**Additional Context**

**Comment by Dodenis** [comment]
Same for me.

The new version now uses https://github.com/api-platform/core/blob/v3.2.0/src/Symfony/Bundle/SwaggerUi/SwaggerUiProvider.php but it does not retrieve the base_url unlike the old https: //github.com/api-platform/core/blob/v3.2.0/src/Symfony/Bundle/SwaggerUi/SwaggerUiAction.php which creates a bug in the Swagger interface because all calls are made without the prefix name from the server

**Comment by soyuka** [comment]
thanks for the bug report
