### ISSUE TITLE
collectionOperations without ItemOperations

### ISSUE THREAD

**Issue by Garfield-fr** [api-platform/core#640]
Hi,

I have this definition on top of my class. I would like to retrieve the collections but not the item. If i deactivate all itemOperations, i have an error.

/**
* @ApiResource(
*     collectionOperations={"get"={"method"="get"}},
*     itemOperations={}
* )
*/
class Facet
{
	...
}

Error message:
"hydra:description": "No route associated with the type "ProviderBundle\Entity\Facet"."

Precision: I use a DataProvider to retrieve the collection

Possible bug or missing configuration ?

**Comment by dunglas** [comment]
It's what I've explained in the other issue. Every resource should at least have a valid GET operation because it's URL is used as identifier and is mandatory for the routing system to work. However

**Comment by Garfield-fr** [comment]
@dunglas Thank's for your answer.

**Comment by teohhanhui** [comment]
Duplicate of #639

**Comment by sbacem** [comment]
I have the same error, I tried to solve it with this route
```php 
....
    /**
     * @Route(
     *     name = "noResult",
     *     path = "/noResult",
     *     defaults = {
     *          "_api_resource_class" = Customer::class,
     *          "_api_collection_operation_name" = "noResult"
     *     }
     * )
     * @Method("GET")
     */
    public function noResultCollectionAction()
    {
        return  null;
    }
...
```
My entity 
```php
....
/**
 * Customer
 *
 * @ORM\Table(name="customer")
 * @ORM\Entity
 * @ApiResource(
 *     itemOperations={},
 *     collectionOperations={
 *           "register"={"route_name"="register", "normalization_context"={"groups"={"register"}}, "denormalization_context"={"groups"={"register"}}}
 *      }),
 */
...
```
But always i have the same error

**Comment by gustawdaniel** [comment]
But what should I do if my specification describe "POST" but do not allow to "GET"?

**Comment by teohhanhui** [comment]
@gustawdaniel You could return HTTP `404` status code on the item `GET` operation.

**Comment by gustawdaniel** [comment]
For further readers:

1) I removed GET path from docs using SwaggerDecorator described [here](https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification)

```
$docs['paths']['/api/my_resource/{id}'] = null;
```

2) I was forced to set `@ApiProperty(identifier=true)` for one of properties.

3) Because of resource was not created I overwrite status code following by https://github.com/api-platform/core/issues/1398

**Comment by gallyamow** [comment]
I set only `@API\ApiProperty(identifier=true)`  and  `itemOperations={ "get"={"status": 404}}` and it solved the promblem

**Comment by Naskalin** [comment]
@Gallyamow This is not entirely true. This is the status if the operation is successful, it can return serialized data if you mark the properties as ``Groups{"read"}`` just with a status of 404. Better use

```
<?php
// api/src/Entity/Book.php

namespace App\Entity;

use ApiPlatform\Core\Action\NotFoundAction;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource(
 *     collectionOperations={
 *         "get",
 *     },
 *     itemOperations={
 *         "get"={
 *             "controller"=NotFoundAction::class,
 *             "read"=false,
 *             "output"=false,
 *         },
 *     },
 * )
 */
 class Book
 {
 }
```
doc link: https://api-platform.com/docs/core/operations/#enabling-and-disabling-operations

**Comment by davispuh** [comment]
I find this to be really annoying, especially because they still appear in docs under `/api`

**Comment by TomaszGasior** [comment]
I need to create `Booking` API entity with no item operations (with no GET operation too) and with only POST (create new) collection operation. Ofc because of current "standard-driven" design of API Platform it does not work ootb but you can, for example, just set different normalization group to make response empty. Unfortunately, this pollutes API documentation.

I found another way to solve this problem. I don't know whether this may use some implementation details of API Platform and I don't know whether it will work in all cases but it works in my case. This is step by step what I did:

1. Temporarily enable GET item operation for your entity.
2. Using `bin/console debug:router` get to know what is the name of route of your entity's GET item operation. Then go to `bin/console debug:router ROUTE_NAME` and inspect details of this route. This is my example output:
```
$ bin/console debug:router api_bookings_GET_item
+--------------+----------------------------------------------------------------+
| Property     | Value                                                          |
+--------------+----------------------------------------------------------------+
| Route Name   | api_bookings_GET_item                                          |
| Path         | /api/bookings/{id}.{_format}                                   |
| Path Regex   | #^/api/bookings/(?P<id>[^/\.]++)(?:\.(?P<_format>[^/]++))?$#sD |
| Host         | ANY                                                            |
| Host Regex   |                                                                |
| Scheme       | ANY                                                            |
| Method       | GET                                                            |
| Requirements | NO CUSTOM                                                      |
| Class        | Symfony\Component\Routing\Route                                |
| Defaults     | _api_item_operation_name: GET                                  |
|              | _api_resource_class: App\Entity\Booking                        |
|              | _controller: api_platform.action.get_item                      |
|              | _format: NULL                                                  |
| Options      | compiler_class: Symfony\Component\Routing\RouteCompiler        |
+--------------+----------------------------------------------------------------+
```
3. Disable GET item operation on your entity.
4. In your routes configuration recreate route originally created by API Platform but change controller path to something else: you can create your own controller or use default provided by API Platform. My example yaml file:
```
api_bookings_GET_item:
    path: /api/bookings/{id}.{_format}
    controller: api_platform.action.not_found
    defaults:
        _api_item_operation_name: GET
        _api_resource_class: App\Entity\Booking
        _format: ~
```

Unfortunately, output from ReadListener (when there is real 404 error) will be different comparing to output from api_platform.action.not_found (when there is our fake 404) because the latter does not have "Not Found" exception message. I can live with that.

This configuration does not allow for GET item operation but it allows to get proper object data inside  response  of POST request on the collection.
