### ISSUE TITLE
Unable to generate an IRI

### ISSUE THREAD

**Issue by fxkopp** [api-platform/core#830]
Hi!

I'm trying to build a custom collection.

AppBundle/Entity:
```
/**
 * @ApiResource(
 *     collectionOperations={
 *         "get"={"method"="GET"},
 *         "event"={"route_name"="place_event"}
 *     },
 *     itemOperations={
 *         "get"={"method"="GET"}
 *     },
 *     attributes={
 *         "normalization_context"={"groups"={"place"}}
 *     }
 * )
 */
class LocalBusiness
{
// ...
}
```

AppBundle/Action:
```
   /**
     * @Route(
     *     name="place_event",
     *     path="/local_businesses/{id}/events",
     *     defaults={"_api_resource_class"=LocalBusiness::class, "_api_collection_operation_name"="event"}
     * )
     * @Method("GET")
     */
    public function __invoke()
    {
        return array('test', 'test');
    }
```

If I try to run this endpoint in Postman, it throws the "Unable to generate an IRI" exception.

Is there anything I can do? 

Thank you so much.

**Comment by GregoireHebert** [comment]
Could you please do the following ? 

- Fork the [API Platform Standard Edition](https://github.com/api-platform/api-platform)
- Do the minimum modification to reproduce the bug
- Post the link in here

We will test that and confirm.

**Comment by Simperfit** [comment]
@fxkopp did you still have the problem ?

**Comment by fxkopp** [comment]
Sorry! No problem is solved 👍

**Comment by cve** [comment]
@fxkopp I have similar issue, how did you solved it?

**Comment by jorgeluisacostaalonso** [comment]
@cve  Have you solved this problem?

**Comment by cve** [comment]
@jorgeluisacostaalonso I don't remember, but I think that was related to the "null id" of the entity

**Comment by jorgeluisacostaalonso** [comment]
@cve Thanks, I have ckecked that too!

**Comment by codedmonkey** [comment]
Had a similar problem, turned out the fields of my resource entity were set to ` private` and since I hadn't created getters and setters at that point the API was unable to generate a route for that entity.

**Comment by codedmonkey** [comment]
I just had the problem for a second time, this time related to custom collection operations.

In my routing definitions, the route for my custom collection operation was positioned before the main API route. For some reason, when the system tries to generate the route for an API resource, it seems to look for collection operations in the route definitions and return the first match. In my case, this was the custom collection operation. My collection operation route also used a mandatory parameter, so the system ultimately fails because it can't find the mandatory parameter. Hopefully it's an understandable story and it clears some things up for others.

So in short, this:

    api_custom_route_name:
        path: '/api/orders/{mandatory}'
        methods:  ['GET']
        defaults:
            _controller: 'Application\Action\CustomAction'
            _api_resource_class: 'Application\Entity\Order'
            _api_collection_operation_name: 'custom'
            
    api:
        resource: '.'
        type:     'api_platform'
        prefix:   '/api'
        
should become this:

    api:
        resource: '.'
        type:     'api_platform'
        prefix:   '/api'

    api_custom_route_name:
        path: '/api/orders/{mandatory}'
        methods:  ['GET']
        defaults:
            _controller: 'Application\Action\CustomAction'
            _api_resource_class: 'Application\Entity\Order'
            _api_collection_operation_name: 'custom'

**Comment by ivelfan** [comment]
@codedmonkey Thanks !! It's works now !!

**Comment by devhero-tech** [comment]
I have the same issue, reason was I forgot to create getter for id ;) maybe I'll save some time for someone else :)

**Comment by YassineYounes** [comment]
I had the same problem, fixed it by adding the getter for the id field

**Comment by xzessmedia** [comment]
> 
> 
> Sorry! No problem is solved 👍

very professional statement inside an issue tracker

**Comment by jawira** [comment]
I had the same problem and I fixed it changing all my entities' fields from `private` to `protected`. 

My fields were `private` because I used _MakerBundle_ (`bin/console make:entity`) to create the entities.

**Comment by piotrekcyk** [comment]
I had the similar problem, my persist method in DataPersister was look like:
![image](https://user-images.githubusercontent.com/17705520/71558133-f9cd8480-2a4f-11ea-89e5-8b3bf111ab2b.png)

I fixed it by call `persist` and `flush` to doctrine, after this this is looking like:
![image](https://user-images.githubusercontent.com/17705520/71558161-56c93a80-2a50-11ea-8b4f-a277bbffa03a.png)

**Comment by Curtisdhi** [comment]
After hours of troubleshooting... @piotrekcyk solution does work... 

Can someone confirm this is the intended behaviour, because it doesn't seem like we should interact with doctrine directly like this.

**Comment by KoketsoMabuela92** [comment]
Hi guys,

I'm also experiencing the IRI issue.

1. Not using Doctrine, using a custom data provider
2. Not using JSONLD, using JSONAPI format

![image](https://user-images.githubusercontent.com/3436524/74542789-e9fcf780-4f4c-11ea-9f8c-03a9e109baa4.png)


...from the above image, it seems it's trying to set the ``_api_write_item_iri`` attribute, however it's failing to ``getIriFromItem``

...any ideas?

**Comment by benblub** [comment]
Hi
i was running in the IRI Problem too. In my case it was a id null Problem.

**Comment by Kolyunya** [comment]
Hi guys!

For me the problem was caused by the fact that I misconfigured the container and none of my data persisters were tagged correspondingly. That's why none of them were working and the api platform could not actually persist the resource.

Would be great though to have some user-friendly exceptions in cases like this, which you can easily detect. Maybe some kind of a check can be added to validate that there actually is at least one data perister.

**Comment by Bersman** [comment]
I had this problem caused because of the identifier I used was not a valid one. 
Tried to use an e-mailaddress as an identifier. IRI did not like that.

**Comment by mirupal** [comment]
same issue, but nothing mentioned here helped.

As a test I was creating objects with `new SomeEntity($id)` in an item provider and got the error which was caused by the missing constructor in the entity. So after adding the constructor to SomeEntity it did work.
```
function __construct($id) {
    $this->id = $id;
}
```

I am using a non-doctrine Entity with custom provider.

**Comment by mescartin** [comment]
I had this problem because the first 'collectionOperation' of the entity was custom with a {slug} param. To make sure Api Platform is able to properly **generate the IRI you must add a default GET operation in your collectionOperations** for the entity.

You should be able to check if this is your case when debugging IriConverter::getIriFromResourceClass(), behaviour explained [here](https://github.com/api-platform/docs/pull/407).

Not working
-----------
```
* @ApiResource(
 *      normalizationContext={"groups"={"issueSubcategory:read"}},
 *      denormalizationContext={"groups"={"issueSubcategory:write"}},
 *      collectionOperations={
 *          "subcategoriesByCategory"={
 *              "method"="GET",
 *              "path"="/issueCategories/{id}/issueSubcategories",
 *              "controller"=IssueSubcategoriesByCategoryController::class,
 *              "read"=false,
 *              "openapi_context"={"summary"="Retrieve all issue subcategories by category"},
 *              "defaults"={"_api_receive"=false}
 *          },
 *      },
 *      itemOperations={
 *          "get"
 *      }
 * )
```


Working
-----------
```
* @ApiResource(
 *      normalizationContext={"groups"={"issueSubcategory:read"}},
 *      denormalizationContext={"groups"={"issueSubcategory:write"}},
 *      collectionOperations={
 *          "get",
 *          "subcategoriesByCategory"={
 *              "method"="GET",
 *              "path"="/issueCategories/{id}/issueSubcategories",
 *              "controller"=IssueSubcategoriesByCategoryController::class,
 *              "read"=false,
 *              "openapi_context"={"summary"="Retrieve all issue subcategories by category"},
 *              "defaults"={"_api_receive"=false}
 *          },
 *      },
 *      itemOperations={
 *          "get"
 *      }
 * )
```

**Comment by Snowbaha** [comment]
@mescartin Thank you ! It helped me a lot!

**Comment by TheDreamatorium** [comment]
I got this error when by using a path parameter on a custom get collection. 
I opted to use a query param instead using 'openapi_context' : 
`        'custom_get_collection' => [
            'path' => '/custom_collection_path',
            'method' => 'get',
            'controller' => CustomGetController::class,
            'openapi_context' => [
                'parameters' => [
                    [
                        'name' => 'client_id',
                        'in' => 'query',
                        'required' => true,
                        'type' => 'integer  ',
                    ]
                ],
            ],
        ],`

Hope it helps someone.

**Comment by digitaltim-de** [comment]
> I had this problem caused because of the identifier I used was not a valid one.
> Tried to use an e-mailaddress as an identifier. IRI did not like that.

So what are you doing then?

**Comment by Montieur** [comment]
@mescartin Thank you! Even though I already had the default GET operation defined, my code still didn't work, but your answer lead me to the solution.
Turns out the ordering of the definitions matters. I had to place the default GET as the first operation, and my custom operation right after that.
